### ISSUE TITLE
Bug: Fails when inital version is 0.0.1

### ISSUE THREAD

**Issue by ntziolis** [jscutlery/semver#102]
When creating a new angular lib via nx the default initial version number of the package is `0.0.1` instead of `0.0.0`. This causes the plugin to fail when executing `nx run mylib:version`. 

When manually setting the version of to 0.0.0 the command starts working as expected.

Root cause is the following line:
https://github.com/jscutlery/semver/blob/8eada0d59864d18b9bcefcfec36068e79dc79c38/packages/semver/src/builders/version/utils/try-bump.ts#L35

Suggestion:
- either add an inital flag in the executer that does something like this:
   ```since: initial || version !== '0.0.0' ? `${tagPrefix}${version}` : null,```
- or at least fail with a more descriptive error telling the users to either:
   - update the version number of the respective package to 0.0.0
   - or create a tag for the current version number manually

**Comment by edbzn** [comment]
Hi @ntziolis, thank you for spotting this! 

Initially we had an --initial-release flag but we removed it as we wanted to make it transparent for the user. It seems to be weak to base our assumption on what's Nx generate (0.0.1), so I would suggest to update the `getCurrentVersion` function with the following logic :

- get the last semver tag
- (first fallback) get the last tag `git describe --tags --abbrev=0`
- (second fallback) get the first commit `git rev-list --max-parents=0 HEAD`

This would also fix users that started to release using another tool with different tag format (without tag prefix for example).

**Comment by ntziolis** [comment]
>  I would suggest to update the `getCurrentVersion` function with the following logic :
> 
> * get the last semver tag
> * (first fallback) get the last tag `git describe --tags --abbrev=0`
> * (second fallback) get the first commit `git rev-list --max-parents=0 HEAD`

That would be perfect.
