### ISSUE TITLE
v1.3.1 Failing silently on large monorepo

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#133]
I have a monorepo with 750+ libraries. When I run

`nx run workspace:version`

The command finishes without any error but there was no version bump and no change logs generated

**Comment by edbzn** [comment]
It was fixed in v1.3.2, when the error was an incorrect git HEAD comparison, it was not logged in the console.

**Comment by bjornharvold** [comment]
1.3.2 has the other issue #132 so I cannot verify
