### ISSUE TITLE
Does semver invalidate Nx caches when the CHANGELOG.md files are created?

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#149]
Hi,

I would like to verify my workflow: 

Steps:

1. Build entire project in develop branch successfully
2. Run your semver plugin
3. Push to master
4. Build everything again in develop branch

At Step 4., has the semver plugin invalidated all the caches for the libraries where it updated the CHANGELOG.md file?

If yes, is there a way to avoid doing that?

Thank you

**Comment by yjaaidi** [comment]
Hi @bjornharvold, thank you for raising this issue.
In fact, semver plugin will implicitly invalidate Nx cache. This isn't something we control (or want to control) as, apparently, Nx will invalidate the cache when any file is added/changed/removed in the project's folder.
In addition to this, it's the desired behavior as CHANGELOG.md is part of the source code and could be used by some custom build commands to generate docs and stuff like that.
