### ISSUE TITLE
Migrations script is not detected by Nx

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/semver#150]
Running `nx migrate @jscutlery/semver` doesn't detect migrations. The `package.json` and `migrations.json` look good though.

Here is the output:
```
Fetching meta data about packages.
It may take a few minutes.
Fetching @jscutlery/semver@2.0.0

>  NX  The migrate command has run successfully.

- package.json has been updated
- there are no migrations to run, so migrations.json has not been created.

>  NX  Next steps:

- Make sure package.json changes make sense and then run 'yarn'
- To learn more go to https://nx.dev/latest/core-concepts/updating-nx
- You may run "nx connect-to-nx-cloud" to get faster builds, Github integration, and more. Check out https://nx.app
```

---

- [ ] once fixed, we have to document the `nx migrate` command.

**Comment by edbzn** [comment]
@yjaaidi I'm not sure it's been fixed, I still get "there are no migrations to run".

**Comment by yjaaidi** [comment]
@edbzn Not sure but I think that there is a gotcha for semver maintainers. Did you try to unlink your local version of @jscutlery/semver?
