### ISSUE TITLE
Allow changing the default header in the changelog

### ISSUE THREAD

**Issue by shlomiassaf** [jscutlery/semver#157]
Hi!

Great work guys, super powerful plugin!

I would like to suggest allowing the user to provide a custom header for the change log.

Currently it defaults to:

---

# Changelog

This file was generated using [@jscutlery/semver](https://github.com/jscutlery/semver).

---

While this is great to promote this plugin and excelent as the default header, users should be able to provide their own header and not being force to promote something.

In the majority of the use cases users will probably not opt out, but some would like to have this option.

Thanks!

**Comment by edbzn** [comment]
Hi, thanks for the issue, I created a PR to address this. Actually, the option uses an inline string so we have to create new lines like this :

```json
"options": {
  "changelogHeader": "# My custom header \n\n"
}
```

I hesitated between a path option pointing to a header.md file, but it seems less simple.

**Comment by yjaaidi** [comment]
👌
