### ISSUE TITLE
git push --atomic failed

### ISSUE THREAD

**Issue by LuckeeDev** [jscutlery/semver#172]
I'm getting this error every time I try to run `nx run workspace:version`. The tag gets pushed to the remote repo, but the commits don't get uploaded. Any idea on how to solve this?

```
√ tagging release v1.11.15
i Run `git push --follow-tags origin main` to publish
git push --atomic failed, attempting non-atomic push
[object Object]
error Command failed with exit code 1.
```

**Comment by LuckeeDev** [comment]
Oof, my bad. I had forgot to pull from the remote.

**Comment by hcharley** [comment]
I think if there isn't an issue open for this, we should find a better way to report the error than `[object Object]`.
