### ISSUE TITLE
FR: Add commitlint, husky and commitizen

### ISSUE THREAD

**Issue by RicardoJBarrios** [jscutlery/semver#175]
The use of `standard-version` is tightly coupled to the use of `conventional-changelog-angular`, and the use of these libraries has become a de facto standard to enforce correct use. It would be nice to allow the installation and configuration of these libraries, even if it is optional.

- [commitlint](https://github.com/conventional-changelog/commitlint): check commit messages to follow the conventional commit pattern
- [husky](https://github.com/typicode/husky): hook into git events and run code at specific points
- [commitizen](https://github.com/commitizen/cz-cli): helper for writing conventional commit messages

I'm now testing the setup of these libraries with semver to ensure that all works well together.

The project [ngx-semantic-version](https://www.npmjs.com/package/ngx-semantic-version) is doing something similar, but focused in Angular apps.

**Comment by edbzn** [comment]
Hey, thanks for the issue, it's a great suggestion!

We can re-use some work done in ngx-semantic-version to set up the dependencies, unfortunately, because this package is not publicly exporting these functions, we have to copy the code.

> I'm now testing the setup of these libraries with semver to ensure that all works well together.

Let me know if you face any issues here.

As we are currently focusing on another feature with semver, we won't take this quickly, but if you want to pick it up I would help you.

**Comment by RicardoJBarrios** [comment]
Hello. Thank you for accepting this feature request.

At the moment everything seems to be working as expected. Now I am finishing a small test project. I finish it, upload it and we see the minimum configuration.

**Comment by edbzn** [comment]
@RicardoJBarrios any update on this?

**Comment by RicardoJBarrios** [comment]
Hello.

Yes, sorry, I've been testing it locally and is configured and working in [https://github.com/RicardoJBarrios/fgc](https://github.com/RicardoJBarrios/fgc). I've found no issues, and all works together with the config in this project, that's basically the default one.

**Comment by RicardoJBarrios** [comment]
@edbzn , I'm not experienced with nx plugins, but I'll try to add this config and create a pull request.

**Comment by edbzn** [comment]
Closed by #203
