### ISSUE TITLE
Remove Angular Devkit dependency

### ISSUE THREAD

**Issue by RicardoJBarrios** [jscutlery/semver#206]
We should allow to use this library without the Angular devkit dependency and use Nx Devkit instead.

**Comment by edbzn** [comment]
Agree, if we are sure it does not drop the support for the regular Angular CLI.

**Comment by RicardoJBarrios** [comment]
Now I't testing it in a  ure Nx project without Angular and fails. I'm changing dependencies and will make a new PR if it works.

**Comment by edbzn** [comment]
I also have seen this issue, thanks! :+1: :fire:
