### ISSUE TITLE
Allowing lerna style tag when detecting last version with git-semver-tags

### ISSUE THREAD

**Issue by floross** [jscutlery/semver#215]
I am migrating my lerna repository to nx and I came accros this project when I needed to publish my packages.

Right now my tags are with the lerna format (`packageJson.name@version`).

The lib you use to fetch the repository came directly with this options [git-semver-tags](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/git-semver-tags#readme) you can pass to it a package name and a lernaTags attributes to get the version from the lerna format tags.

It could be good to get this options to simplify the lerna workspace to nx workspace portage.

When reading the code semver should read the `package.json` name key and set the `lernaTags` and `package` to the `gitSemverTags` function if a `lernaTagStyle` options is selected and should add this options to the target configuration.

What do you think about these feature request ?

**Comment by edbzn** [comment]
Hey, I like the idea and it would be definetely useful for some situations!

**Comment by edbzn** [comment]
Should be fixed by #256
