### ISSUE TITLE
Ignored --version and --preid in sync mode

### ISSUE THREAD

**Issue by WilliamChelman** [jscutlery/semver#236]
Hello there! 😃 

I just started using this lib, but I encountered an issue trying to run it in sync mode. The issue is that --version and/or --preid options seem to be ignored in my case.

To reproduce:

1. clone [this repository](https://github.com/WilliamChelman/jscutlery-semver-sync-bug)
2. run `npm ci`
3. run `npm run nx -- run workspace:version --version=prerelease --preid=alpha --dry-run`

For now, this results in a version being 0.0.2 in both packages, where I would have expected to see something like 0.0.2-alpha.1 or something similar (I'm still currently in the process of grasping all those keywords though).

Looking at the first log of the cmd though, we can see

```
> nx "run" "workspace:version" "--version=prerelease" "--preid=alpha" "--dry-run"
> nx run workspace:version --preid=alpha --dry-run --dryRun 
```

So it looks like the version option is swallowed somewhere 🤔. Might the issue come from nx itself maybe? (also tried with nx 12+, same issue)

**Comment by edbzn** [comment]
Hi, this should be fixed in 2.8.1 using `--releaseAs=...` instead of `--version=...`.
