### ISSUE TITLE
Getting  message No previous version tag found, fallback to version 0.0.0 even though we have tagged everything

### ISSUE THREAD

**Issue by BurtV** [jscutlery/semver#251]
I  created a new branch to reset all the tags andmake sure  we tagging all our apps and libraries. 
re-ran  the command to generate a changelog for all our apps/libs
Pushed all  changes and also made sure all the tags were pushed.

Merged everything  back into master. 

Created  a  new branch from the new master branch. 
Made 1  change  to a  core library.  and  ran the nx affected command to tag and add entries to change logs. 

all my apps failed with :
🟠 No previous version tag found, fallback to version 0.0.0.
New version will be calculated based on all changes since first commit.
If your project is already versioned, please tag the latest release commit with onboarding-web-component-e2e-x.y.z and run this command again.
✔ tagging release onboarding-web-component-e2e-0.1.0
fatal: tag 'onboarding-web-component-e2e-0.1.0' already exists

Command failed: git tag -a onboarding-web-component-e2e-0.1.0 -m chore(release): 0.1.0
fatal: tag 'onboarding-web-component-e2e-0.1.0' already exists

This is correct as the tags exist. So not sure why the version command isnt picking up  the correct previous version. 

any ideas around this?

**Comment by edbzn** [comment]
Hi @BurtV, can you confirm that the last tag and the version defined in package.json are in sync? for example, if you tagged `onboarding-web-component-e2e-0.1.0`, the version in package.json should be `0.1.0`.

**Comment by jafaircl** [comment]
Any updates on this? Also running into this issue.

**Comment by edbzn** [comment]
It's hard to tell without replication but I think this can occur for the following reason, the tag was created but not targeting any `mainBranch` commit checksum. I would investigate more if I can dive into the Git history.

**Comment by jafaircl** [comment]
Ok here is a reproduction repo: https://github.com/jafaircl/semver-testing

When running `nx run new-lib:version --releaseAs=minor` on the `attempt-new-minor-version` branch, here is the error I get:

```
🟠 No previous version tag found, fallback to version 0.0.0.
New version will be calculated based on all changes since first commit.
If your project is already versioned, please tag the latest release commit with new-lib-x.y.z and run this command again.
✔ bumping version in /Users/jonathanfaircloth/Projects/semver-testing/packages/new-lib/package.json from 0.1.0 to 0.1.0
✔ outputting changes to /Users/jonathanfaircloth/Projects/semver-testing/packages/new-lib/CHANGELOG.md
✔ committing /Users/jonathanfaircloth/Projects/semver-testing/packages/new-lib/package.json and /Users/jonathanfaircloth/Projects/semver-testing/packages/new-lib/CHANGELOG.md and all staged files
✔ tagging release new-lib-0.1.0
fatal: tag 'new-lib-0.1.0' already exists

Command failed: git tag -a new-lib-0.1.0 -m chore(release): 0.1.0
fatal: tag 'new-lib-0.1.0' already exists

Error: Command failed: git tag -a new-lib-0.1.0 -m chore(release): 0.1.0
fatal: tag 'new-lib-0.1.0' already exists

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Socket.<anonymous> (node:internal/child_process:448:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)

———————————————————————————————————————————————

>  NX   ERROR  Running target "new-lib:version" failed

  Failed tasks:

  - new-lib:version

  Hint: run the command with --verbose for more details.
```

Is it possible that using "squash and merge" to merge pull requests is causing it?

**Comment by edbzn** [comment]
> Is it possible that using "squash and merge" to merge pull requests is causing it? Or should we only be running the release command from the main branch?

Yes, I think this is the problem, the tag is created with a commit reference that disappears when you squash and merge. Tags are not updated on their own. IMO you should always version on the main branch.

**Comment by jafaircl** [comment]
Ok. My solution to this was to switch to the main branch, delete the tag for the release with `git tag -d my-library-0.1.0` and then run ` nx run my-library:version --releaseAs=minor` once to create the 0.1.0 release. Now, when I try to create a 0.2.0 release, everything works as expected. Thanks for your help!
