### ISSUE TITLE
fix: v2.5.0 Cannot read property 'Symbol(@angular-devkit/architect:builder)' of undefined

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#254]
Just upgraded to v2.5.0 of your plugin and running Nx v12.6.5

Got this error right away

```
> nx run workspace:version 
Cannot read property 'Symbol(@angular-devkit/architect:builder)' of undefined
```

Thoughts?

**Comment by edbzn** [comment]
Hi, thanks for reporting, I'm aware of this issue, it was not caught by the tests unfortunately. I will fix it asap.

**Comment by edbzn** [comment]
A new version `@jscutlery/semver@2.6.0` was released.

**Comment by wSedlacek** [comment]
@edbzn I am having this same issue on another project, what was the solution?

**Comment by edbzn** [comment]
Should be fixed the Angular devkit is not a dependency anymore. Can you give me more context?

**Comment by wSedlacek** [comment]
I am trying to fix https://github.com/ngneat/tailwind
And the end to end test give me this error.

So your solution was just not to use the Angular DevKit but use the Nx one instead?

**Comment by edbzn** [comment]
> And the end to end test give me this error.

The end to end test? What's the point with semver?

> So your solution was just not to use the Angular DevKit but use the Nx one instead?

Should be transparent for you, we are using the Nx devkit instead of the Angular one.

@wSedlacek Can you send me an URL, something I can dig into to debug?

**Comment by wSedlacek** [comment]
> The end to end test? What's the point with semver?

😅 The question was unrelated to semver, however when I searched up the error on Google this issue was literally the only thing I found.
Haha, I think I got it fixed now though, thank you for your help!
