### ISSUE TITLE
ng-add schematic

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#28]
The user should be able to add `@jscutlery/semver` in a workspace using a schematic.

- install the package
- ask options (remote, branch, push and syncVersions)
- update the `workspace.json` or `angular.json` accordingly

**Comment by yjaaidi** [comment]
Depending on the answer to `syncVersions`, we should apply the version builder to all projects (one by one) or the whole workspace.
```json

    "workspace": {
      "root": "",
      "architect": {
        "version": {
          ...
        }
      }
    },
```

⚠️ We should also add the `workspace` project to `nx.json` if it does not exist.
