### ISSUE TITLE
Allow empty versionTagPrefix

### ISSUE THREAD

**Issue by miluoshi** [jscutlery/semver#281]
Currently if I set value of `versionTagPrefix` to empty string, it is replaced with `"v"` in synced mode.

I believe the reason is that the property value is not checked against `undefined` [here](https://github.com/jscutlery/semver/blob/main/packages/semver/src/executors/version/index.ts#L33).

We are using tags in format `x.y.z` without `v` prefix and this prevents us from using this executor.

**Comment by edbzn** [comment]
Closed by #283
