### ISSUE TITLE
Copy root README.md to dist

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#31]
It could be useful for some usecases, firstly for this package which have poor documentation on npm.

It could be an option `--copy-root-readme`

![image](https://user-images.githubusercontent.com/8522558/103166279-d71baa80-4820-11eb-9ba7-67becd002a5b.png)

**Comment by edbzn** [comment]
Close since we can use the `assets` option from build builder to copy assets in dist.

**Comment by yjaaidi** [comment]
Yup! In most cases we will want to have a specific README for each package.
