### ISSUE TITLE
NPM publish

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#32]
It could be useful to publish to npm directly using this package. It could be a new builder.

**Comment by yjaaidi** [comment]
We'll have to handle:
- [ ] Prompting the user for OTP
- [ ] Using tokens in env vars for the CI (another issue)?

**Comment by yjaaidi** [comment]
https://github.com/bikecoders/ngx-deploy-npm is interesting but it doesn't work with nx as it checks for configurations in `angular.json`.
It's probably easier to fix it than to reinvent it.
We can then extend our `ng-add` schematic to install `ngx-deploy-npm` and configure it for publishable libraries.

**Comment by yjaaidi** [comment]
Closing this issue to regroup the discussions here #167.
