### ISSUE TITLE
Refactor `tagPrefix` chained ternary

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#323]
Extract and refactor logic related to the tag prefix. 

https://github.com/jscutlery/semver/blob/a0691cc7ca514c0471d3a5d29cc81843d07666d5/packages/semver/src/executors/version/index.ts#L34

It should not use a chained ternary and also be extracted in a dedicated function.

**Comment by edbzn** [comment]
Hi @RaviTejaVattem,

I would expect a pure function that we can test in an isolated context: 

```ts
export function resolveTagPrefix({ 
  versionTagPrefix,
  projectName,
  syncVersions,
}: { 
  versionTagPrefix: string | null | undefined; 
  projectName: string; 
  syncVersions: boolean; 
}): string {
  if (versionTagPrefix !== undefined) {
    return resolveInterpolation(...);
  }
  if (syncVersions) {
    return 'v'
  }
  return `${projectName}`
}
```

This is easy to test, would you want to take it?

**Comment by RaviTejaVattem** [comment]
Thank you for the explanation.

Sure I want to try.

I will create a draft PR. We will decide if I can do this after you reviewing it.
