### ISSUE TITLE
Customize commit message

### ISSUE THREAD

**Issue by TriPSs** [jscutlery/semver#333]
Would be awesome if we could define a custom commit message or change the default template to also contain the target name, we now get a lot of commits like:
- chore(release): 2.1.3
- chore(release): 1.0.1
- etc

Would prefer to see something like
- chore(release): App one v2.1.3
- chore(release): App two 1.0.1
- etc

**Comment by edbzn** [comment]
I changed the title to have something more generic.

**Comment by wSedlacek** [comment]
Being able to add `[skip ci]` is important so that GitHub actions doesn't preform and infinite loop

**Comment by wSedlacek** [comment]
If any is interested I created a patch that can be applied with `patch-package` until this is fixed.
```
diff --git a/node_modules/@jscutlery/semver/src/executors/version/version.js b/node_modules/@jscutlery/semver/src/executors/version/version.js
index 9f3383a..929f35a 100644
--- a/node_modules/@jscutlery/semver/src/executors/version/version.js
+++ b/node_modules/@jscutlery/semver/src/executors/version/version.js
@@ -60,6 +60,7 @@ function _runStandardVersion({ bumpFiles, dryRun, projectRoot, newVersion, noVer
         path: projectRoot,
         preset,
         tagPrefix,
+        releaseCommitMessageFormat: 'chore(release): {{currentTag}} [skip ci]',
         skip: {
             changelog: skipChangelog,
         },

```
