### ISSUE TITLE
Bump version only if necessary

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/semver#35]
`version` schematic should add a `latest` git tag. This can be used as a base when running version on affected projects: `nx affected --target version --base latest`

**Comment by edbzn** [comment]
We should also add the tag prefix `<project>-latest` for independent versions to avoid conflicts.

**Comment by yjaaidi** [comment]
The more I think about this, the more I wonder if it's up to the builder to tag.
There is a real challenge with independent mode. If we use a different tag for each project then we won't be able to use `nx affected` and we'll have to build our own mechanism to check which projects should be bumped.

If we use `nx affected` then we can tag `latest` but if we run `version` manually then we shouldn't tag `latest`.

I can see two different approaches:
1. Let the CI handle the tagging. This is more flexible as users can run `version` then `ngx-deploy-npm` then anything and finally tag `latest` but it's less convenient and out of the box.
2. `nx run workspace:version` should run `nx affected --target version --base latest`

**Comment by edbzn** [comment]
One other approach would be to simply avoid the `latest` tag with independent mode, it does not have a meaning to have one single tag for many packages at the same time. 

Regarding the `nx affected` command, we can simply replace the need of the latest tag using GitHub refs.

```
nx affected:build --base=origin/master --head=${{ github.event.pull_request.head.ref }}
```

or 

```
nx affected:build --base=origin/master --head=${{ github.event.push.head.ref }}
```

Do we bring this feature for the synced mode at least? This discussion raise doubts about the whole thing.

**Comment by yjaaidi** [comment]
I think that we have to find a solution that solves the following issues:

# 1. The nx affected base
The problem with the `origin/master` approach is failing builds.
Suppose one or more builds fail _(e.g. libs `a`, `b`, `c` should bump but as something goes wrong with `a`, they don't)_, then we fix that in one commit that only affects one of them _(e.g. lib `a`)_ then some libs won't be bumped _(e.g. `b` & `c`)_ while they should.

We need a `latest` tag that marks the last time that we were able to bump & deploy all apps and libs... or any other generic solution but I can't think of anything easier and as robust as a tag.

# 2. Publishable packages

We have to publish all packages before tagging & pushing the `latest` tag.

# 3. Deployable apps

We have to deploy apps before tagging & pushing the `latest` tag.
As apps deployment is out of our scope, we have to separate the `version` & `tag-latest` steps.

---

I think that the CI workflow should look something like:
```sh
nx affected --base refs/tags/latest version
nx affected --base refs/tags/latest deploy
nx run workspace:tag-latest
```

... or maybe, we should forget about tags, make `version` idempotent and run it on all projects:
```sh
nx run-many --all --target version
nx affected --base refs/tags/latest deploy
```

It feels wrong to run `version` on all projects all the time instead of enjoying the benefits of `nx affected` but at least we don't pollute git with additional tags. What do you think @edbzn? I'll rename the issue to be less influencing.
