### ISSUE TITLE
Prompt for projects list when user chooses independent mode

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/semver#36]
`ng-add` schematics should prompt user to select the projects to version.

- [x] By default, all projects should be selected.
- [x] The prompt is dynamic (it depends on the projects list) so we can't use `x-prompt`. We have to hack our way through the `PromptProvider` (Cf. https://github.com/angular/angular-cli/blob/7a39938cd0373eaee75597b96909b747e3094f18/packages/angular_devkit/schematics_cli/bin/schematics.ts) or just use inquirer directly.
- [x] add ˋprojects` option to override the prompt

**Comment by edbzn** [comment]
The last missing feature for this is the option projects override.
