### ISSUE TITLE
Semver is generating the same version

### ISSUE THREAD

**Issue by dianjuar** [jscutlery/semver#375]
We integrated continuous deployment on Nx Plugin [ngx-deploy-npm](https://github.com/bikecoders/ngx-deploy-npm) and we're using Semver and its `postTargets` feature to trigger the deployment.

For some reason, Semver generates the same version when there is nothing new, you can see it here ->
https://github.com/bikecoders/ngx-deploy-npm/runs/4091615454?check_suite_focus=true

This causes an unwanted behavior and an error because the tag already exists on the repo.
```txt
✔ bumping version in ./packages/ngx-deploy-npm/package.json from 3.0.4 to 3.0.4
✔ outputting changes to ./packages/ngx-deploy-npm/CHANGELOG.md
✔ committing ./packages/ngx-deploy-npm/package.json and ./packages/ngx-deploy-npm/CHANGELOG.md and all staged files
✔ tagging release v3.0.4
fatal: tag 'v3.0.4' already exists

Command failed: git tag -a v3.0.4 -m chore(release): 3.0.4
fatal: tag 'v3.0.4' already exists
```

The weird thing is when I run this locally it has the expected behavior, do not generate a version

![image](https://user-images.githubusercontent.com/7026066/140187247-d3f09708-d745-4844-9994-7e17c09df313.png)

**Comment by edbzn** [comment]
I checked your repo and saw nothing suspicious, if it's not reproducible locally the issue certainly comes from the CI, but I can't figure it out. Previously I had a similar issue caused by a wrongly formatted tag, semver was failing to decide the last version. I have to dig a bit.

**Comment by dianjuar** [comment]
I wanted to publish a fix but it continues to bump the same version, the 3.0.4

https://github.com/bikecoders/ngx-deploy-npm/runs/4100180134?check_suite_focus=true

I haven't test it out locally

**Comment by dianjuar** [comment]
I got it.

The problem was with my repo; for some reason, the last tag wasn't correctly; it wasn't on the commit that should be on master, so I just deleted the tag, generated by hand again in the right commit, and pushed it to master. After that, everything is working as expected.

The steps to catch the error were, clone the repo in a separate folder and check for the tags on master; there, I realized that the last version wasn't there.

Maybe I messed it up when I was implementing the Continuous Deployment somehow.

**Comment by edbzn** [comment]
Interesing, thanks for the explanation that could probably help us debugging such behavior in the future.

**Comment by edbzn** [comment]
@aderito7 could you verify that the already existing tag `my-app-0.92.0` targets a `baseBranch` reference, otherwise, it will throw `fatal: tag already exists` because the tag is not reachable for calculating the new version.

**Comment by aderito7** [comment]
> @aderito7 could you verify that the already existing tag `my-app-0.92.0` targets a `baseBranch` reference, otherwise, it will throw `fatal: tag already exists` because the tag is not reachable for calculating the new version.

This seems to make a difference.
Is it preferable for jscutlery/semver to have it's own config for the `baseBranch` as _main_ rather than use what's in the nx.json?
```javascript
// nx.json
  "affected": {
    "defaultBase": "custom-branch"
  },
```

**Comment by edbzn** [comment]
@aderito7 I opened an issue for that, would love to see your contribution!

**Comment by aderito7** [comment]
Been monitoring making use of `--base-branch`. It worked alright for a few days.
Seems that it's back to giving use the error that tag already exists.

```
> nx run my-app:version --base=d496cd3ef1 --baseBranch=master --releaseAs=minor 
✔ outputting changes to /builds/apps/my-app/CHANGELOG.md
✔ committing all staged files and %s
Nothing specified, nothing added.
hint: Maybe you wanted to say 'git add .'?
hint: Turn this message off by running
hint: "git config advice.addEmptyPathspec false"
✔ tagging release my-app-0.49.0
fatal: tag 'my-app-0.49.0' already exists
Command failed: git tag -a my-app-0.49.0 -m chore(release): 0.49.0
fatal: tag 'my-app-0.49.0' already exists
Error: Command failed: git tag -a my-app-0.49.0 -m chore(release): 0.49.0
fatal: tag 'my-app-0.49.0' already exists
    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)
———————————————————————————————————————————————
>  NX   ERROR  Running target "my-app:version" failed
  Failed tasks:
  
  - my-app:version
  
  Hint: run the command with --verbose for more details.
```
