### ISSUE TITLE
Nx install can't format .commitlintrc.js

### ISSUE THREAD

**Issue by ChazUK** [jscutlery/semver#383]
When installing @jscutlery/semver with `nx g @jscutlery/semver:install` an error is listed in the console.

```
Could not format .commitlintrc.js. Error: "Unexpected token, expected ";" (2:12)
  1 | {
> 2 |   "extends": [
    |            ^
  3 |     "@commitlint/config-angular"
  4 |   ],
  5 |   "rules": {}"
```

`.commitlintrc.js` actual contains JSON data, not valid JavaScript, so the file should be renamed `.commitlintrc.json` to allow nx to automatically format it.

**Comment by edbzn** [comment]
Hi, just fixed this. Thanks for reporting!
