### ISSUE TITLE
Feature: Ignore hidden types when calculating if anything has changed

### ISSUE THREAD

**Issue by wSedlacek** [jscutlery/semver#399]
Under the context of a normal release, (not a releaseAs) I want the release to only happen if there are changes that require a release. Typically this this is going to be `feat` and `fix`, however one could make the argument for `pref`.

With the current version, it seems to only look at if there are commits, not what type there are.

**Comment by edbzn** [comment]
This is a great idea! Could be done after #397.

**Comment by edbzn** [comment]
Fixed by #504
