### ISSUE TITLE
Monorepo independent versioning

### ISSUE THREAD

**Issue by yjaaidi** [jscutlery/semver#4]
When using a monorepo, developers can choose independent versioning:
- a library should be bumped only if its files change,
- every lib should have its own git tags.

[standard-version](https://github.com/conventional-changelog/standard-version) doesn't handle commits filtering per directory.
Maybe we should  use lerna's libraries. Cf. https://github.com/lerna/lerna/blob/main/core/conventional-commits/lib/recommend-version.js

**Comment by yjaaidi** [comment]
We should use `standardVersion`'s `tagPrefix` parameter in order to prefix tags for each package with the package's name (e.g. `@jscutlery/semver@0.1.1`).

**Comment by edbzn** [comment]
@yjaaidi I'm wondering if we can run a builder on multiple projects at once. Do you have any clue about this ?

**Comment by yjaaidi** [comment]
Not sure. I just think that as it acts globally on the repo, it doesn't have to be a builder. It could be just a schematic.

**Comment by yjaaidi** [comment]
Well as we just tested, it actually already works in independent mode perfectly.
