### ISSUE TITLE
Option to skip changelog generation for independent versioning mode

### ISSUE THREAD

**Issue by TheUnderScorer** [jscutlery/semver#402]
Hello!

Is there any reason why for independently versioned projects the skip option for changelogs is not supported? I've checked the code and found this 😄 :

https://github.com/jscutlery/semver/blob/5799d016dbd143341966c62a9936e1201fa67d95/packages/semver/src/executors/version/index.ts#L96-L104

Would it be possible to change that? I can even submit PR with it, but I'm asking first to know if this is intended or not.

Thanks for the plugin, working with it was great so far!

**Comment by edbzn** [comment]
Hi, never needed it so it's not supported, sure you can open a PR.

**Comment by edbzn** [comment]
@TheUnderScorer This is fixed in `2.17.5`, thanks for reporting this.
