### ISSUE TITLE
Changelog is always empty

### ISSUE THREAD

**Issue by nidomiro** [jscutlery/semver#412]
I need help in figuring out why my Changelog is always empty: https://github.com/nidomiro/ts-tools/blob/main/packages/config-helper/CHANGELOG.md
Also every version bump is a patch-bump, maybe this correlates with the Changelog issue.

What am I doing wrong?

**Comment by edbzn** [comment]
Hi, that's the actual behavior, we need refactoring to handle deps commit message cf #417 & #314.

**Comment by nidomiro** [comment]
Sometimes it displays the commits in the changelog.
On a first look it seems to correlate with breaking-change commits: `feat(abc)!: my desc`.
Version config-helper@0.3.1 was a breaking-change, but not recognized as such by semver.

**Comment by Bielik20** [comment]
I have notices that using `!` doesn't work. You can try and commit like so:
```
feat: my message

BREAKING CHANGE: something big
```

**Comment by edbzn** [comment]
I'm going to close this, feel free to reopen if this is not resolved.
