### ISSUE TITLE
changelog on dependency update is empty

### ISSUE THREAD

**Issue by hoonoh** [jscutlery/semver#417]
Hi, I am very new to this plugin and have a question on changelogs. (Not sure, but it could be related to #412)

I noticed that changelog description is generated as expected when there are commits directly affecting the versioned app or lib, but when there are changes with the dependencies, the description (commit messages) which relates to the dependency is always missing.

This often times results in releases with no description at all, and it would be nice to have messages such as `dependency [name] updated to version 1.0.0`.

**Comment by edbzn** [comment]
Hi, this needs refactoring to be able to do this, cf #314. Definitely a feature we would like to have.

**Comment by hoonoh** [comment]
Hi, thanks for the info. I will watch #314 and try helping out whenever I can.
