### ISSUE TITLE
Weird behaviour when tagging with semver:version

### ISSUE THREAD

**Issue by nicolashzmor** [jscutlery/semver#418]
I'm trying to configure a GitLab-ci pipeline for a GitHub project. (Not sure if relevant, but just in case)

I'm using the following executors' config:

```
"release": {
  "builder": "@jscutlery/semver:version",
  "options": {
    "commitMessageFormat": "release(${projectName}): release version ${version} [skip-ci]",
    "postTargets": ["nx-appwrite:deploy"]
  }
},
"deploy": {
  "builder": "ngx-deploy-npm:deploy",
  "options": {
    "access": "public",
    "buildTarget": "production",
    "dryRun": true,
    "noBuild": true,
    "tag": "${tag}"
  }
}
```

and getting the following error:

```
> nx run api-interfaces:release 
Non releasable module
> nx run nx-appwrite:release 
🟠 No previous version tag found, fallback to version 0.0.0.
New version will be calculated based on all changes since first commit.
If your project is already versioned, please tag the latest release commit with nx-appwrite-x.y.z and run this command again.
✔ bumping version in /builds/doesrobbiedream/core/libs/nx-appwrite/package.json from 0.1.0 to 0.1.0
✔ created /builds/doesrobbiedream/core/libs/nx-appwrite/CHANGELOG.md
✔ outputting changes to /builds/doesrobbiedream/core/libs/nx-appwrite/CHANGELOG.md
✔ committing /builds/doesrobbiedream/core/libs/nx-appwrite/package.json and /builds/doesrobbiedream/core/libs/nx-appwrite/CHANGELOG.md and all staged files
✔ tagging release nx-appwrite-0.1.0
fatal: tag 'nx-appwrite-0.1.0' already exists
Command failed: git tag -a nx-appwrite-0.1.0 -m release(nx-appwrite): release version 0.1.0 [skip-ci]
fatal: tag 'nx-appwrite-0.1.0' already exists
Error: Command failed: git tag -a nx-appwrite-0.1.0 -m release(nx-appwrite): release version 0.1.0 [skip-ci]
fatal: tag 'nx-appwrite-0.1.0' already exists
    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Socket.<anonymous> (node:internal/child_process:448:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
———————————————————————————————————————————————
>  NX   ERROR  Running target "release" failed
  Failed tasks:
  
  - nx-appwrite:release
```

Any lights on this issue will be really appreciated :)

**Comment by edbzn** [comment]
Hi @nicolashzmor, it seems the tag `nx-appwrite-0.1.0` already exists on your Git remote, so the executor fails to create the tag as it cannot overwrite it. If you remove the tag on GitLab UI and then rerun it should succeed. Let me know if it helps you.

**Comment by nicolashzmor** [comment]
He @edbzn that's the weird behaviour. There are no tags on the project yet.

![Screen Shot 2021-12-29 at 8 55 46 AM](https://user-images.githubusercontent.com/66749276/147659723-3920470f-50d7-4f00-9291-6e4522811b98.png)

Actually the program recognize that:

```
🟠 No previous version tag found, fallback to version 0.0.0.
New version will be calculated based on all changes since first commit.
```
and later it says that the tag already exists 😕

**Comment by edbzn** [comment]
Agree it's weird, sources are closed? I would need to inspect the repository.

**Comment by nicolashzmor** [comment]
Not at all, is an open project. 

https://github.com/robbiesdream/core

**Comment by nicolashzmor** [comment]
If you'd like to see the pipelines: https://gitlab.com/doesrobbiedream/core/-/pipelines

**Comment by nicolashzmor** [comment]
I'd be happy to join you in a live review, maybe I can be of assistance. Just let me know.

**Comment by edbzn** [comment]
There's an existing tag `nx-appwrite-0.1.0` but the release commit was not pushed, you should remove the tag or retag a commit that is currently pointing to a `main` reference and then rerun the release.

**Comment by nicolashzmor** [comment]
Oh okay, I see now that the tags are written inside the Gitlab repository, but never pushed to Github.
Not being able to push to Github though. When trying to push the tags it returns a 403 error. 😕

**Comment by edbzn** [comment]
I've never really experienced mirror repos, do the versioning work in GitLab now?

**Comment by nicolashzmor** [comment]
I decided to fall back to Gitlab and mirror GitHub by pushing... because it was a mess. 
I still have the same problem though.

```
No previous version tag found, fallback to version 0.0.0.
New version will be calculated based on all changes since first commit.
If your project is already versioned, please tag the latest release commit with nx-appwrite-x.y.z and run this command again.
✔ bumping version in /builds/doesrobbiedream/nx-core/libs/nx-appwrite/package.json from 0.0.0 to 0.0.1
✔ created /builds/doesrobbiedream/nx-core/libs/nx-appwrite/CHANGELOG.md
✔ outputting changes to /builds/doesrobbiedream/nx-core/libs/nx-appwrite/CHANGELOG.md
✔ committing /builds/doesrobbiedream/nx-core/libs/nx-appwrite/package.json and /builds/doesrobbiedream/nx-core/libs/nx-appwrite/CHANGELOG.md and all staged files
✔ tagging release nx-appwrite-0.0.1
fatal: tag 'nx-appwrite-0.0.1' already exists
Command failed: git tag -a nx-appwrite-0.0.1 -m release(nx-appwrite): release version 0.0.1 [skip-ci]
fatal: tag 'nx-appwrite-0.0.1' already exists
Error: Command failed: git tag -a nx-appwrite-0.0.1 -m release(nx-appwrite): release version 0.0.1 [skip-ci]
fatal: tag 'nx-appwrite-0.0.1' already exists
    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1062:16)
    at Socket.<anonymous> (node:internal/child_process:448:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
```
I cannot understand where is the tag being stored, as the project doesn't have any tag registered, I deleted cache from the pipelines.

I don't understand how if the push is never submitted, semver still has some state that's reading to say nx-appwrite-0.0.1 is already tagged.

**Comment by nicolashzmor** [comment]
The code repo is now: https://gitlab.com/doesrobbiedream/nx-core

**Comment by nicolashzmor** [comment]
Just to clarify: The tag is actually there but is not accessible for cleanup.
 
I added this just to keep going, but this is not a good approach I assume.
```
if [ "$(git tag -l ${GHOST_TAGS})" ]; then
  git tag -d "${GHOST_TAGS}"
fi
```

But this states that the tag is actually there because it does delete it (would fail otherwise).

But, could this be prevented somehow? 
Do you understand why is there a persisted state of a tag is haven't been pushed?

**Comment by nurbashanghai** [comment]
Did u try to delete all local tags? I also had this issue, but then I just cleaned all local git tags on my machine 
`git tag -d $(git tag -l)`
And it worked.
Im not sure if it helps, but hey try it

**Comment by nicolashzmor** [comment]
hey @nurbashanghai, yes, actually in local I don't have this problem. My problem is that I'm using a CI pipeline, so I need to run that command to ensure that there are no local tags on the pipeline. There are two things there: 
The pipeline is not stateless and the _remove ghosts tags_ step seems unnecessary to me...

**Comment by edbzn** [comment]
@nicolashzmor Maybe the tag was pushed to another ref than your base branch and therefor is not detected by semver but git throws when trying to create the tag.

**Comment by edbzn** [comment]
I'm closing this, feel free to reopen if not resolved.
