### ISSUE TITLE
Feature request: Update tag on the built package.

### ISSUE THREAD

**Issue by nicolashzmor** [jscutlery/semver#419]
I have the following scenario.

I want to `lint`, `test` and `build` in prod mode all the affected packages beforehand because before going into release mode and creating tags and updating the package.json or building the docker image, etc, I want to be sure that everything is in order.

The issue is that while the tag is created and pushed to the repository correctly, the package was built before this, so it doesn't have the `dist/libs/lib-name/package.json` updated.

```
> nx run nx-appwrite:release 
✔ bumping version in /builds/doesrobbiedream/nx-core/libs/nx-appwrite/package.json from 0.0.2 to 0.1.0
✔ outputting changes to /builds/doesrobbiedream/nx-core/libs/nx-appwrite/CHANGELOG.md
✔ committing /builds/doesrobbiedream/nx-core/libs/nx-appwrite/package.json and /builds/doesrobbiedream/nx-core/libs/nx-appwrite/CHANGELOG.md and all staged files
✔ tagging release nx-appwrite-0.1.0
ℹ Run `git push --follow-tags origin HEAD` to publish
📦 Skipping build
+ @doesrobbiedream/nx-appwrite@0.0.2
npm notice 
npm notice package: @doesrobbiedream/nx-appwrite@0.0.2
```

So I ended up with the tag 0.1.0 on my repository, but the package has the previous tag: 0.0.2.

I think that when this happens, 
```
bumping version in /builds/doesrobbiedream/nx-core/libs/nx-appwrite/package.json from 0.0.2 to 0.1.0
```
Could it be that semver updates the package.json inside the /dist folder (which is the one that for example ngx-deploy-npm is using to deploy)?

How off-track would that be? I mean, for now, I can just set the `noBuild: false` on the deploy and re-build it. 
I definitely don't want to lose the previous stage of checking if the build goes well.

I understand that is really sketchy practice to update the distribution after build... but I don't know how can this be achieved.

**Comment by edbzn** [comment]
@nicolashzmor What about rebuilding after the release step? The downside is that you build twice (one before the release to check the build correctness and one after to publish an updated `package.json`). That's what we do in this repo. 

One other way would be to use the ngx-deploy-npm `--package-version` option along with post-targets interpolation, this option will write to your distribution `package.json`. Something like:

 ```jsonc
     "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "postTargets": ["my-project:publish"]
      }
    },
    "publish": {
      "executor": "ngx-deploy-npm:deploy",
      "options": {
        "access": "public",
        "packageVersion": "${version}" // <- overwrite dist package.json
      }
    }
  }
 ```
 
 But I think I would prefer the first option, building twice as you are sure to publish exactly what's expected.

**Comment by nicolashzmor** [comment]
Yeah, I'm actually doing as you are. I like the packageVersion idea though, but again... Is a little bit sketchy to touch the dist once is built.

Thank you for everything! :) 
Everything seems to be working right now.
