### ISSUE TITLE
Dedicated sub CHANGELOGs with Sync mode

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#42]
For now we only have one root CHANGELOG for the monorepo. There is some interest of having sub CHANGELOGs : 
- more concise and readable
- optimized for release bots (eg [@releasebutler](https://twitter.com/releasebutler?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor))
- ? 

Fun fact: Lerna made this feature early, before they included a root CHANGELOG as an enhancement, [see this](https://github.com/lerna/lerna/blob/main/CHANGELOG.md#rocket-enhancement-5).

It could be a new option for the version builder. We can use the [`standard-changelog`](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/standard-changelog) package to generate sub CHANGELOGs.

**Comment by yjaaidi** [comment]
In fact, the sub changelog is more important but it wasn't the quickest solution with `standard-version` 😊. 
In addition, it helps users know why they update if some commits are generic or if they miss the scope.

It doesn't have to be option. Actually, what should be the option is the root changelog. What do you think?

I guess we should call https://github.com/conventional-changelog/standard-version/blob/master/lib/lifecycles/changelog.js that wraps `standard-changelog` and updates the file.

**Comment by edbzn** [comment]
> It doesn't have to be option. Actually, what should be the option is the root changelog. What do you think?

Agree with that, but it's a major change. Let's go for it.

**Comment by glebmachine** [comment]
Looking forward this feature!

**Comment by edbzn** [comment]
@glebmachine I'm working on this, it will be available soon. :blush:

**Comment by edbzn** [comment]
@glebmachine We published a release including this feature.

**Comment by glebmachine** [comment]
I'm found that if no previous tag was set, cli command exits silently.
![image](https://user-images.githubusercontent.com/1610882/106267924-6c082e00-623b-11eb-8363-97c34a656c68.png

And one more thing)
Is it possible to calculate Changelog for each library in parallel?
I've got about 50 libraries and it takes for ages

Here concat can be replaced with combineLatest or similar 
https://github.com/jscutlery/semver/blob/968356806a22c6676c63cd067d20628ae2ccf3f9/packages/semver/src/builders/version/version.ts#L33

**Comment by edbzn** [comment]
@glebmachine I will investigate the bug, thank you. Nice suggestion for the parallelization. :+1:

**Comment by edbzn** [comment]
@glebmachine I'm not able to reproduce the bug, can you send us a reproduction?

**Comment by yjaaidi** [comment]
I just opened an issue for changelog parallelization.
