### ISSUE TITLE
Bump to a specific version

### ISSUE THREAD

**Issue by Nxtivision** [jscutlery/semver#424]
Hi,

First, thanks for this very useful plugin which helps us a lot! 👍

I already have some versions available for some internal projects, already published (e.g.: project-one-0.2.1)
I would like to know if it is possible to bump directly to a specific version (e.g.: project-one-13.0.0)
We would like to define major versions with the same major version of Angular ("the entire major version of this lib is compatible with Angular v13")

Do you know how we could achieve this? I already tried to specify these versions in tags but they are overwritten by the automatic versioning

Thank you in advance and have a wonderful day!

**Comment by edbzn** [comment]
Hi @Nxtivision, sorry for the late reply I'm lazy at the beginning of this year. You can force the version you want to release and skip the automated versioning by using the `--releaseAs` option. The downside is that you cannot automatize this task, you will need to run the command by hand.
