### ISSUE TITLE
Feature: Configure changelog commit and issue url format

### ISSUE THREAD

**Issue by rtkac** [jscutlery/semver#434]
Hi, is it possible to add configuration for generated CHANGELOG?
Same as it has [Standard Version](https://github.com/conventional-changelog/standard-version#configuration) in `.versionrc` config file.

The problem is that the Changelog does not have correct url of the Bitbucket commits/tags compare and no url of the Jira tickets.

**EXAMPLE OF USAGE:**
```
{
  "commitUrlFormat": "https://comp.bitbucket.com/projects/PROJECT-REPO/commits/{{hash}}",
  "compareUrlFormat": "https://comp.bitbucket.com/projects/PROJECT-REPO/compare/commits?targetBranch=refs/tags/{{previousTag}}&sourceBranch=refs/tags/{{currentTag}}",
  "issueUrlFormat": "https://comp.jira.com/browse/{{prefix}}{{id}}",
  "issuePrefixes": ["PROJECT1-", "PROJECT2-"]
}
```

It will be great feature, thanks!

**Comment by gauravsoni119** [comment]
I think this is more or less related to #397 issue. @edbzn is there any planning to support `.versionrc` file in the upcoming versions.

**Comment by edbzn** [comment]
@gauravsoni119 Nothing planned for this but contributions are welcome!

**Comment by rtkac** [comment]
@gauravsoni119 @edbzn something new here?
Thanks :)

**Comment by rtkac** [comment]
Hi @edbzn, it's already done I believe... right? I can see it in the documentation.
Thanks

**Comment by menosprezzi** [comment]
@rtkac where?

**Comment by edbzn** [comment]
We don't have `.versionrc` file support but you can configure the changelog config using the executor options [commitParserOptions](https://github.com/jscutlery/semver#customizing-the-commit-parser), and [preset](https://github.com/jscutlery/semver?tab=readme-ov-file#customizing-conventional-changelog). Does this help?

**Comment by rtkac** [comment]
Right, that's what I was talking about :)
