### ISSUE TITLE
Docs: include ALL notes

### ISSUE THREAD

**Issue by atomicrobokid** [jscutlery/semver#436]
Hello,

Firstly thanks for this plugin, it's exactly what i've been looking for!

I'm wondering how you include all git messages from all conventional commits when you generate a release?

I can't work it out from the README file, under "Only new notes" you have an identical block of code as an example as the one above it:

```
{
  "targets": {
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "postTargets": ["my-project:github"]
      }
    },
    "github": {
      "executor": "@jscutlery/semver:github",
      "options": {
        "tag": "${tag}",
        "generateNotes": true
      }
    }
  }
}
```

Removing `generateNotes` does nothing. Git releases show only the latest commit message since the last release. Ideally I'd want to see every change that has been added since the last release but can't see that as an option. I can't see how the above code is either `Only new notes` or `All notes` 🤔

**Comment by edbzn** [comment]
Hi, I think it's related to #397. Does it?

**Comment by wSedlacek** [comment]
The `generateNotes` uses the GitHub CLI which only goes off of PRs.
The `${notes}` is new notes added to the `CHANGELOG.md` in the `version` step.

I have been thinking about this recently and I think we can improve the way the `${notes}` work, I might take another pass at it sometime soon @edbzn

**Comment by edbzn** [comment]
@wSedlacek Nice! Excited to see what you have in mind.

**Comment by edbzn** [comment]
I'm going to close this, feel free to reopen if it is not resolved.
