### ISSUE TITLE
Error: error: src refspec main does not match any

### ISSUE THREAD

**Issue by maheshambiga** [jscutlery/semver#440]
The following error is shown when the versioning command is run,
```
nx run button:version --releaseAs=prerelease --preid=beta --skipRootChangelog --push
```

```
Error: error: src refspec main does not match any
error: failed to push some refs to 'https://**.git'
```
It works as expected when the same command from the log is run.
```
✔ bumping version in libs/button/package.json from 0.0.1-beta.1 to 0.0.1-beta.2
✔ outputting changes to libs/button/CHANGELOG.md
✔ committing button/package.json and libs/button/CHANGELOG.md and all staged files
✔ tagging release button-0.0.1-beta.2
ℹ Run git push --follow-tags origin feature/versioning` to publish
```
Running **git push --follow-tags origin feature/versioning** in CLI works as expected.

**Comment by edbzn** [comment]
@maheshambiga What is your default branch? `main` branch seems not to be your default branch.

**Comment by maheshambiga** [comment]
@edbzn - ```main``` is not my default branch. I am expecting the changes to be pushed to the current upstream branch.

**Comment by maheshambiga** [comment]
@edbzn  Setting ```--baseBranch``` seems to have solved the issue. 
Closing the issue. Thank you.
