### ISSUE TITLE
"Nothing changed since last release." instead of release

### ISSUE THREAD

**Issue by limonte** [jscutlery/semver#442]
I'm unable to trigger the releasing process from CI, it always says "Nothing changed since last release"

Here's the commit history:

<img width="528" alt="CleanShot 2022-02-15 at 15 50 50@2x" src="https://user-images.githubusercontent.com/6059356/154065563-db2bd812-80fd-4f18-a9bc-afa908f9f0f9.png">

### Expected behavior

The new patch release of `eslint-config` package is made because the last commit has `fix(eslint-config): `

### Actual behavior

<img width="652" alt="CleanShot 2022-02-15 at 15 52 01@2x" src="https://user-images.githubusercontent.com/6059356/154065748-6860e587-51f4-4c3e-98d0-3e5eac054821.png">

---

Here's the latest CI build where the error can be observed: https://github.com/sweetalert2/sweetalert2-monorepo/actions/runs/1847004641

Here's the GitHub actions config that was used for the latest build: https://github.com/sweetalert2/sweetalert2-monorepo/blob/main/.github/workflows/release.yml

I'm probably missing something small here, but can't figure out what. Any help would be appreciated 🙇

**Comment by edbzn** [comment]
@limonte A new release is only created if one file under the project root is modified. Files in your workspace root won't trigger a new release, even if you specified the scope in the commit message.

**Comment by limonte** [comment]
That was it, thank you for your amazing work in maintaining this project @edbzn!

**Comment by michelepatrassi** [comment]
@edbzn run into this after merging dependabot PRs which bumped packages in the root package.json. NX correctly detected apps have changed but no bump happened:
```
❯ npx nx affected --target version --base=origin/main~1 --head=HEAD --dryRun

 >  NX   Running target version for 2 project(s):

    - wallpaper
    - mobile-renderer
   
   With flags:
     --dryRun=true

 ———————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run wallpaper:version --dryRun

[wallpaper] 🟢 Nothing changed since last release.

> nx run mobile-renderer:version --dryRun

[mobile-renderer] 🟢 Nothing changed since last release.

 ———————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target version for 2 projects
```
This is confusing :/ I would expect the output from NX (two affected apps) to be used by the executor to bump the version based on the last commit. 

Is this a bug or desired behaviour? As it is, major dependency changes lead to the same app version

**Comment by edbzn** [comment]
@michelepatrassi This is the desired behavior, in order to detect changes, semver checks if any file changed in the **project root**.
