### ISSUE TITLE
Unable to release version 

### ISSUE THREAD

**Issue by DanielRivers** [jscutlery/semver#450]
When I try to release a version on a fresh install I am getting the following error

```
⧗   input: chore(utils-interfaces): release version 0.1.0
✖   type must be one of [build, ci, docs, feat, fix, perf, refactor, revert, style, test] [type-enum]
```

It looks like chore has been removed from the allowed values. 

@nrwl/cli: 13.8.3
@jscutlery/semver: "^2.19.3

**Comment by edbzn** [comment]
Hi @DanielRivers, `chore` commits were removed from the angular conventional config and replaced by `build` or `ci`. If you want to support them you can disable the check when semver create the version using the `--noVerify` option, or you can also twik the commit lint config by removing `@commitlint/config-angular` and using `@commitlint/config-conventional` instead. In this repository, we are using the `--noVerify` option.
