### ISSUE TITLE
Setup CHANGELOG.md automatically

### ISSUE THREAD

**Issue by BioPhoton** [jscutlery/semver#458]
When running `` the first time and ther is no `CHANGELOG.md` file present i get the following error:

Error: fatal: pathspec 'path/to/lib/CHANGELOG.md' did not match any files

In such a case we could create the file if it does not exist

**Comment by edbzn** [comment]
Should be fixed.

**Comment by karlwills** [comment]
I still seem to be having this issue, should we be creating CHANGELOG's manually if it is still happening?

**Comment by edbzn** [comment]
I cannot reproduce, I'm going to close this. Feel free to reopen and provide reproduction steps.

**Comment by Chowarmaan** [comment]
This issue still exists.  I just added the versioning to a new project in an existing workspace, and the first time I run the version, even with dry-run, it generates the error.  The CHANGELOG.md file does not exist in my project.

    nx generate @jscutlery/semver:ng-add

    >  NX  Generating @jscutlery/semver:ng-add

    √ Would you want to enforce conventional commits? (Y/n) · true
    √ Which preset would you want to use? · conventional
    ? Which projects would you want to version independently? 
        UPDATE apps/timesheets/project.json
        UPDATE apps/timesheets-e2e/project.json
        UPDATE package.json

    > ngcc --properties es2020 browser module main
    > husky install

    husky - Git hooks installed
    up to date, audited 1861 packages in 6s

    found 0 vulnerabilities

Then when I try to run the version with the short command line I get the error:

    $ nx version --dry-run --project=timesheets

    > nx run timesheets:version --dry-run=true

    [timesheets] 🟠 No previous version tag found, fallback to version 0.0.0.
        New version will be calculated based on all changes since first co
        If your project is already versioned, please tag the latest releasts-x.y.z and run this command again.
    [timesheets] 🆕 Calculated new version "0.1.0".

    [timesheets] 📜 Generated CHANGELOG.md.
    [timesheets] ❌ Error: fatal: pathspec 'apps\timesheets\CHANGELOG.md' did not match any files

    at node_modules\@jscutlery\semver\src\executors\common\exec.js:10:34
       at ChildProcess.exithandler (node:child_process:395:5)
       at ChildProcess.emit (node:events:527:28)
       at maybeClose (node:internal/child_process:1090:16)
       at ChildProcess._handle.onexit (node:internal/child_process:302:5)

I am running this on GIT Bash on Windows.  If I create the CHANGELOG.md file, this works without error.

**Comment by edbzn** [comment]
Maybe it's happening only on Windows because on Linux I can't reproduce.
