### ISSUE TITLE
package.json is always 0.0.1

### ISSUE THREAD

**Issue by fokkerone** [jscutlery/semver#464]
My package.json version number isn´t updated accordingly 
That is my worklfow 
. change a file
```git add .
git commit -m"message / not following conventional commits"

yarn nx run nextapp:version
```
output

✔ outputting changes to /Users/fokker/Desktop/gerd/apps/nexter/CHANGELOG.md
✔ committing all staged files and %s

✔ tagging release next-0.0.6 
ℹ Run `git push --follow-tags origin master` to publish

```
git tag


next-0.0.3
next-0.0.4
next-0.0.5
next-0.0.6
(END)

yarn nx run next:build 
or 
yarn nx run next:build:production 

```

dist/app/nextApp package.json becomes: 
```
{
...
  "version": "0.0.1",
...
}

```

Expected behavoir: 
```
{
...
  "version": "0.0.6",
...
}
```

**Comment by edbzn** [comment]
Hi @fokkerone, do you mean that the generated distribution `package.json` file is not picking up the right version from the development one? I think this is an Nx issue as semver does not deal with the generated `package.json`. Can I access a repository to reproduce?

**Comment by fokkerone** [comment]
https://github.com/fokkerone/nxsemvernextdemo

**Comment by fokkerone** [comment]
And as you mentioned here https://github.com/nrwl/nx/issues/2457 the semvernx plugin solves exactly this problem

**Comment by edbzn** [comment]
@fokkerone You need to commit the `package.json` file in your next project, update to the right version, and try to re-build the app. Nx should use the project's `package.json` to generate the distribution one with the correct version.

**Comment by fokkerone** [comment]
Doing this would be against NX Mental Model...

I solved it in now with maybe the dumbest node npm script:

```
#!/usr/bin/env node
const { exec } = require('child_process');

process.chdir('./dist/apps/nexter');

exec('git describe --tags', (error, stdout, stderr) => {
  if (error) {
    console.error(`git error: ${error}`);
    return;
  }

  const version = stdout.split('-')[1];
  exec(`npm version ${version}`, (error, stdout, stderr) => {
    if (error) {
      console.error(`npm error: ${error}`);
      return;
    }
    console.log(`stdout: ${stdout}`);
    console.error(`stderr: ${stderr}`);
  });
  console.error(`stderr: ${stderr}`);
});
```
Finally I call this via postTarget after a successfull version.

Since version updating is needed for publishable libs and apps locally as NPM packages or in CI/CS pipelines it could be integrated after all. 

Tagging and changelogs.md are super useful features, but changing version for npm release (! Not everyone can use ngx-deploy-npm:deploy postTargets) needs to be implemented in azure/circelCI, gitlab ... etc. to be implemented, so I don't understand why this is not integrated.
That certainly goes with the CLI but I have not been able to find (NX docu is say: not very userfriendly ;-) )

Sorry but a per app/lib package.json would be really stupid, then I would need no NX/monorepo.
