### ISSUE TITLE
Crash when using Nx 13.9.0 and above

### ISSUE THREAD

**Issue by lukelukes** [jscutlery/semver#467]
This commit introduced some breaking changes: https://github.com/nrwl/nx/commit/48a5d19b68b8478861dff462eea04bdb6b27f674

Error:
`Cannot find module '@nrwl/tao/src/shared/params'`

'@nrwl/tao/src/shared/params' needs to be replaced with: 'nx/src/shared/params'

I see the Nx versions are currently pinned.

**Comment by edbzn** [comment]
This has been fixed in `2.21.1`, thanks for the bug report.
