### ISSUE TITLE
loosing the current version of package

### ISSUE THREAD

**Issue by HackPoint** [jscutlery/semver#475]
✔ bumping version in /Users//dev/work-projects//libs/ui/package.json from 1.2.0 to 0.1.0
✔ committing all staged files and %s
✔ committing /Users//dev/work-projects//libs/ui/package.json and all staged files
✔ tagging release ui-e2e-0.1.0
✔ tagging release ui-0.1.0
ℹ Run `git push --follow-tags origin main` to publish
ℹ Run `git push --follow-tags origin main` to publish

How is that possible that it doesn't track the correct version of the package?

I think you need to add more documentation about it!

**Comment by ianldgs** [comment]
I'm getting a similar error:

```
> nx run test-npm:version

✔ outputting changes to /Users/iserpa/projects/my-project/libs/test-npm/CHANGELOG.md
✔ bumping version in /Users/iserpa/projects/my-project/libs/test-npm/package.json from 0.0.6 to 0.0.6
✔ committing /Users/iserpa/projects/my-project/libs/test-npm/package.json and all staged files
✔ tagging release test-npm-0.0.6
fatal: tag 'test-npm-0.0.6' already exists

Command failed: git tag -a test-npm-0.0.6 -m release(test-npm): version 0.0.6 [ci skip]
fatal: tag 'test-npm-0.0.6' already exists

Error: Command failed: git tag -a test-npm-0.0.6 -m release(test-npm): version 0.0.6 [ci skip]
fatal: tag 'test-npm-0.0.6' already exists

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

**Comment by edbzn** [comment]
@HackPoint For your information versions are tracked through git tags, maybe something is wrong here. I need more context to help you.

@ianldgs Basically this error is thrown when a version tagged `test-npm-0.0.6` is already created but the commit is not attached to your configured `baseBranch`.

**Comment by ianldgs** [comment]
Hey @edbzn! Thanks for your reply. That was exactly the problem. I re-tagged my libraries manually to fix it.

**Comment by HackPoint** [comment]
> sically this error occurs when a version tagged `test-npm-0.0.6` is already created but the commit is not attached to your configured `baseBranch`.

How do you tag the libraries using your lib?

**Comment by ianldgs** [comment]
> > sically this error occurs when a version tagged `test-npm-0.0.6` is already created but the commit is not attached to your configured `baseBranch`.
> 
> How do you tag the libraries using your lib?

I manually created tags for my libraries on gitlab, pointing to the latest commit on master.

Fortunately, I'm in the early phases and I don't have that many libraries.

The reason I didn't have the tags was a wrong `git push` command, using `--follow-tags` instead of `--tags`.

**Comment by HackPoint** [comment]
> 

What if I would like to use this library to promote my tagging and versioning?
What is the cmd for that?
@ianldgs @edbzn

**Comment by ianldgs** [comment]
@HackPoint whenever you run the `version` executor it suggests that you do a `git push --follow-tags`, since it creates the tags locally, but doesn't push them. Should be enough if you put it on your CI after the version bump command

**Comment by edbzn** [comment]
I'm not sure if it answers your question @HackPoint but this library uses semver to calculate the version, the tag is created accordingly to that version. If you want to release and specify your own version you can use the `--releaseAs` option. This will skip the version calculation and just create the version you want. Then you can use the `--push` option if you want to push the version on your remote repository.

**Comment by edbzn** [comment]
I'm gonna close this, if you still need help be free to reopen.
