### ISSUE TITLE
Dry-run mode is broken

### ISSUE THREAD

**Issue by ms-tng** [jscutlery/semver#497]
In the current version `2.23.2`, the dry-run mode seems to be broken.

To reproduce, follow these steps:
* `npx create-nx-workspace --preset=core`

In the folder created by `create-nx-workspace`:
* `npm install -D @jscutlery/semver`
* `npm install -D @nrwl/react`
* `nx g @nrwl/react:lib mylib --publishable --importPath="@myorg/mylib"`
* `nx g @jscutlery/semver:install`
* `echo "// some change" >> packages/mylib/src/index.ts`
* `git add packages/mylib/src/index.ts`
* `git commit -m "feat: some feature"`
* `nx version mylib --dryRun --skipProjectChangelog`

It produces the following error:
```
[mylib] � No previous version tag found, fallback to version 0.0.0.
        New version will be calculated based on all changes since first commit.
        If your project is already versioned, please tag the latest release commit with mylib-x.y.z and run this command again.
[mylib] � Calculated new version "0.1.0".
[mylib] ❌ Error
    at REDACTED\node_modules\@jscutlery\semver\src\executors\common\exec.js:10:34
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

Also, the `package.json` file of `mylib` is modified although it shouldn't be in dry-run mode.
Without the `--dryRun` flag, everything works fine.

**Environment:**
* @jscutlery/semver 2.23.2
* git version 2.35.2.windows.1
* OS: Windows 10 21H2 19044.1645

**Comment by edbzn** [comment]
Hi, thanks for the report and the reproduction steps. I will investigate.
