### ISSUE TITLE
Fix: drop standard-version as it is deprecated

### ISSUE THREAD

**Issue by Zamiell** [jscutlery/semver#509]
When installing this plugin with yarn:

```
[1/4] Resolving packages...
warning @jscutlery/semver > standard-version@9.3.2: standard-version is deprecated. If you're a GitHub user, I recommend https://github.com/googleapis/release-please as an alternative.
```

**Comment by Zamiell** [comment]
More info: https://github.com/conventional-changelog/standard-version/issues/909

**Comment by edbzn** [comment]
We made some refactor recently to drop standard-version but we still use it in one place to generate changelogs, it would be nice to entirely drop it.

**Comment by edbzn** [comment]
We can swap `standard-version` with the `conventional-changelog` package.
