### ISSUE TITLE
improvement: template string replacement for nested structures like gitlab release executor assets

### ISSUE THREAD

**Issue by ndrsg** [jscutlery/semver#523]
Hi!
First of all, thanks for this really useful project!

I have played around a bit and found a problem with the @jscutlery/semver:gitlab executor.

The following will fail if the gitlab-release executor is placed in the postTargets as followed:

```json
"version": {
  "executor": "@jscutlery/semver:version",
  "options": {
    "preset": "conventional",
    "commitMessageFormat": "chore(${projectName}): release version ${version}",
    "postTargets": [
      "my-project-name:release"
    ]
  }
},
"release": {
  "executor": "@jscutlery/semver:gitlab",
  "options": {
    "tag": "${tag}",
    "description": "${notes}",
    "assets": [
      {
        "name": "asset-${version}-win64.zip",
        "url": "https://my-server.com/asset-${version}-win64.zip"
      }
    ]
  }
},
```

I went through the code and think to understand, that we only replace template variables on the first level, and also never for arrays. Is this correct?

https://github.com/jscutlery/semver/blob/f7d717f170e1e2e4427181604cf2841661e748c5/packages/semver/src/executors/version/utils/post-target.ts#L75

```ts
export function _getTargetOptions({
  options = {},
  context,
}: {
  options?: Record<string, unknown>;
  context: Record<string, unknown>;
}): Record<string, unknown> {
  return Object.entries(options).reduce(
    (optionsAccumulator, [option, value]) => {
      const resolvedValue =
        typeof value === 'object'
          ? value
          : coerce(
              createTemplateString(
                (value as number | string | boolean).toString(),
                context
              )
            );

      return {
        ...optionsAccumulator,
        [option]: resolvedValue,
      };
    },
    {}
  );
}
```

Maybe it is possible to walk through options recursively and replace template variables everywhere. That would be also really useful for the *@nrwl/workspace:run-commands* executor.

**Comment by edbzn** [comment]
Resolved in #524, that was fast!
