### ISSUE TITLE
:bug: fix: Plugin hangs at random during generation of 1000+ change log files

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#528]
Hi!

First, thank you for a GRRRRRRREAT plugin 🚀

Does exactly what we need as part of our release strategy.

We have a monorepo with 1000+ modules and we generate change log files for every module. At random times, the plugin will just hang during change log generation (see below) and never come back to life. Most times it works as it should.

Our command:
`npx nx run workspace:version --trackDeps=true`

```
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
[workspace] 📜 Generated CHANGELOG.md.
```

We tried changing our command to:
`npx nx run workspace:version --skipProjectChangelog=true`

...and that works well.

We don't really need change log files in every module so we are ok with the alternate command. 

Just noting this down as an inconvenience.

🍺

**Comment by edbzn** [comment]
Hi @bjornharvold, thanks for the feedback. 

Well, I can also notice that the logs look terrible in sync mode. :smile: Regarding the problem you described, we are running the changelog in parallel and we delegate the generation to standard-version, maybe there's a memory leak somewhere. 

I think we can find something using the node profiler, your environment (1000+ modules) is pretty large, so it's not easy for me to replicate, if you have time and you are up to, could you run the profiler in your project and give me the outputs?

You can run it this way: 

```bash
node --prof node_modules/@nrwl/cli/bin/nx.js run demo:version
```

**Comment by bjornharvold** [comment]
Hi @edbzn 

Yes I can. The problem is this issue is random so I don't know if I will be able to get to it. Many times, introducing a profiler, also changes how the program is run and the error doesn't come to light.

Will see what I find and report back.

**Comment by bjornharvold** [comment]
Hi @edbzn 

Not able to replicate with the profiler. Changed my script to call:

`npx nx run workspace:version --skipProjectChangelog=true`

Will leave it at that.

Thank you 🍺
