### ISSUE TITLE
Original indentation of package.json not preserved after running version executor

### ISSUE THREAD

**Issue by fabsrc** [jscutlery/semver#531]
After running the `version` executor, all versioned package.json files are indented with two spaces. If the original indentation was not two spaces and there is no prettier pre-commit hook configured to fix the formatting, the files need to be formatted manually afterwards.

Checking the code, I see that the indentation is [currently hardcoded to `2`](https://github.com/jscutlery/semver/blob/4eaa43929140cfd2527dc5d9e3f919be7d647685/packages/semver/src/executors/version/utils/project.ts#L64). Would it be possible to preserve the original indentation when updating package.json files?

For example: npm's `version` command [uses the `json-parse-even-better-errors package`](https://github.com/npm/cli/blob/b46fed75379979a6be86ac72117a90f8ad3b3a99/workspaces/libnpmversion/lib/read-json.js#L5) for parsing package.json files which adds symbols for `indent` and `newline` to the parsed data that are then [used when writing the file again](https://github.com/npm/cli/blob/b46fed75379979a6be86ac72117a90f8ad3b3a99/workspaces/libnpmversion/lib/write-json.js#L8-L11).

**Comment by edbzn** [comment]
Hi @fabsrc, thanks for the suggestion, I like it. Would you want to contribute?
