### ISSUE TITLE
prerelease and breaking change commit behaviour

### ISSUE THREAD

**Issue by 051181** [jscutlery/semver#532]
I would like to know if there is a way to bump into a beta major if there is a breaking change.
Ex:
prev version: 1.0.1
....
BREAKING CHANGE
...
next version: 2.0.0-beta.0
thank you

**Comment by edbzn** [comment]
Hi @051181, could you try `nx run my-project:version --releaseAs=premajor --preid=beta`?

**Comment by 051181** [comment]
Hi @edbzn , i've tried what you suggested but that configuration bumps ever to the next major, even if no breaking changes are made. (This is part of an automated ci/cd pipeline so i have no way to know if next version will be a major, a minor or a patch).
Maybe i misunderstood something about semver and the correct plugin use?

**Comment by edbzn** [comment]
Ok I got it, well it's not possible, as soon as you pass `--releaseAs`, semver never uses the commit history to calculate the version, if you want to bump a major you have to precise it. This option is not meant to be used in a CI.

**Comment by 051181** [comment]
ok thank you for the clarification.. i will try a different way to solve the problem!
