### ISSUE TITLE
Question: Differences between semver process and nx build process with affected argument

### ISSUE THREAD

**Issue by Jucian0** [jscutlery/semver#555]
Hello everyone, foremost thanks for this amazing package!

I have a question about the process of build and the process of generate new version with `semver`.
In my monorepo I have some packages that depend on a principal package. When I run my pipeline to update the principal package, `semver`, run for all packages, but increase the version just for the principal package, but nx build and nx publish try to build, and publish all packages, because all packages are affected by this change. However, the npm does not allow publishing the same package again with the same version, so it falls.
````
>  NX   Running target version for 15 project(s):
    - core
    - pagination
    - primitives
    - grid
 
> nx run pagination:version
[pagination] 🟢 Nothing changed since last release.
> nx run primitives:version
[primitives] 🟢 Nothing changed since last release.
> nx run grid:version
[loader] 🟢 Nothing changed since last release.
....
> nx run core:version
[core] 🆕 Calculated new version "0.0.3".
[core] 📜 Generated [CHANGELOG.md](http://changelog.md/).
[core] 📝 Updated [package.json](*****************/src/acc969a934aa7c9a9dd672c728de8199786cc413/package.json) version.
[core] 📦 Committed "chore(core): release version 0.0.3 [skip ci]".
[core] 🔖 Tagged "@*******-ui/core@0.0.3".
[core] 🚀 Pushed to "origin" "master".`
Should `semver` up the version of all affected packages too?

NX   Running target build for 15 project(s) and 1 task(s) they depend on

NX   Running target publish for 14 project(s):

**Comment by edbzn** [comment]
Hi @Jucian0, if the dependent packages are not updated it's because their sources have not changed. You can try to use the `--trackDeps` in all of your packages, this should bump and publish packages at any depth.

**Comment by Jucian0** [comment]
Hi, thanks for answer, I was going to try --allowEmptyRelease, I will try  - - trackDeps. Thanks @edbzn

**Comment by edbzn** [comment]
Oh you are right, `--allowEmptyRelease` would solve it, not `--trackDeps`, let me know!
