### ISSUE TITLE
Cannot find project 'workspace' when running `nx run workspace:version`

### ISSUE THREAD

**Issue by avchugaev** [jscutlery/semver#557]
### Pre-conditions

- Nx workspace generated with the latest version Nx for Angular v14 
- Single Angular lib configured by `@jscutlery/semver:install`
- `project.json` has a `version` configuration:
```json
"version": {
  "executor": "@jscutlery/semver:version",
  "options": {
    "baseBranch": "master",
    "preset": "angular",
    "tagPrefix": "${projectName}@"
  }
}
```

### Steps to reproduce

Run the command

```bash
nx run workspace:version
```

### Actual result

An error:

```bash
 >  NX   Cannot find project 'workspace'
```

### Expected result

A successful run of versioning.

**Comment by edbzn** [comment]
Hi @avchugaev, did you run the install generator with `--syncVersions` or select the sync mode when prompted? This should configure the sync mode.

**Comment by avchugaev** [comment]
Hey @edbzn, I think I ran it without `--syncVersions`. Just like said in README.
Give me a moment to re-check. 
Btw, which versioning mode is better for a workspace containing publishable Angular libraries, given some of them depends on others?
