### ISSUE TITLE
Feature Request: Bump versions explicitly based on passed in parameters

### ISSUE THREAD

**Issue by KyleBastien** [jscutlery/semver#56]
It would be great to be able to bump versions explicitly based on a passed in parameter. This is similar in nature to Lerna's [`version`](https://github.com/lerna/lerna/tree/main/commands/version#readme) command.

I think this command could look like:

```
# would patch all affected packages
nx affected --target version --semver-type patch
# would patch all packages
nx run workspace:version --semver-type patch
```

**Comment by yjaaidi** [comment]
Thanks for the issue @KyleBastien.
This is not exactly where we are headed as we are focusing on automation thanks to conventional commits.
On the other side, this could be interesting for some specific use cases or when not using conventional commits yet.

We should cover the following features:
- [ ] ˋversion patch|minor|major`
- [ ] `version x.y.z`

PRs are welcome 😊

**Comment by edbzn** [comment]
That's not the first time I see this suggestion from users that have projects not following the conventional commits, it would be a great addition for manual versioning.
