### ISSUE TITLE
Using version: 2 in workspace.json has no effect. Project still believes it's v: 1 because of semver customization

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#568]
Hi,

I've had some back and forth chat with nx.dev guys on this here:
[https://github.com/nrwl/nx/issues/10354](https://github.com/nrwl/nx/issues/10354)

In a nutshell, due to the semver plugin configuration in workspace.json, every time I create a new module, it gets created inline because Nx sees the workspace definition containing semver configuration and interprets it as being an inline project.

So it doesn't matter which version I indicate. My project always gets interpreted as a version: 1 type workspace. As a result, I have to run Nx convert workspace after each module. 

Here's the offending code.

```
"workspace": {
      "root": ".",
      "targets": {
        "version": {
          "executor": "@jscutlery/semver:version",
          "options": {
            "syncVersions": true,
            "commitMessageFormat": "chore(${projectName}): release version ${version}"
          }
        }
      }
    }
```

Is this code needed? Is there anything to be done with custom configuration?

Please advise,
Bjorn

**Comment by edbzn** [comment]
Hi @bjornharvold,

The virtual "workspace" project is a bit of a hack, it's not super reliable in the long run, that's why I opened an issue https://github.com/nrwl/nx/issues/10002, this is something I would like to refactor. 

Have you tried moving the virtual "workspace" project into a root "project.json", you can see an [example here](https://github.com/BedrockStreaming/forms).

Let me know if it helps.

**Comment by bjornharvold** [comment]
Hi @edbzn 

I'm afraid that doesn't work. I tried removing the workspace over to root project.json in different ways but your plugin couldn't find it.

**Comment by bjornharvold** [comment]
Just to be clear what I did. I made my project.json look identical to the example you gave. But it complained saying it couldn't find "workspace".

**Comment by bjornharvold** [comment]
I found the "workspace": "." in workspace.json. Once I added that, your plugin was able to find the configuration. This solves my issue.

Thank you
