### ISSUE TITLE
--skipCommit flag does not work

### ISSUE THREAD

**Issue by mikhnikonov** [jscutlery/semver#575]
Running `nx run project:version --skipCommit` twice on the same project on the second time will still update the package.json and will generate an empty changeLog and will create an additional commit, even thou there are no changes between fist run and the second

I can create an empty nx repo to demonstrate if necessary

**Comment by edbzn** [comment]
Hey @mikhnikonov, why did you close the issue?

**Comment by mikhnikonov** [comment]
Hello @edbzn 
I found out that it was in issue on my end, that in my version target options I had

>   "version": {
>       "executor": "@jscutlery/semver:version",
>       "options": {
>         "preset": "conventional",
>         "trackDeps": true,
>         "skipCommit": true,
>         "allowEmptyRelease": false,
>         "releaseAs": "patch"
>       }
>     },

And the last `releaseAs` did trigger the version bump and the changeLog creation and the commit
After removing it `skipCommit` did work as expected

But now I have to figure out how to release my package always as a patch 🤷

**Comment by edbzn** [comment]
Nice, let me know if you need help.
