### ISSUE TITLE
Changelog Generation (.md Header levels)

### ISSUE THREAD

**Issue by LRR1993** [jscutlery/semver#582]
Is this a way so that the generated changelog.md of the new version, arent at the same level of the version title.

Current
```
### [2.0.4](https://github.com/...) (2022-08-24)

### Dependency Updates

* `common` updated to version `0.0.2`

### Bug Fixes
...etc
```

Desired Result 
```
## [2.0.4](https://github.com/...) (2022-08-24)

### Dependency Updates

* `common` updated to version `0.0.2`

### Bug Fixes
...etc
```

Current config
```
  "targets": {
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional",
        "changelogHeader": "# ...Changelog"
      }
    }
  }
```

**Comment by tuffz** [comment]
I think this problem has already been fixed, as it does not appear in my changelogs, f.ex https://raw.githubusercontent.com/tuffz/tuffz-nx-workspace/main/apps/ericbuettner-com/CHANGELOG.md

**Comment by edbzn** [comment]
Great, thanks @tuffz. What is your experience with `--trackDeps` so far?

**Comment by tuffz** [comment]
@edbzn I'm very happy with it, the only thing that bothered me yesterday was that I couldn't find how to change the headline of the section.

After I put emojis everywhere in front of it, dependency updates as headline still remain without emoji, f.ex. https://github.com/tuffz/tuffz-nx-workspace/blob/main/apps/ericbuettner-com/CHANGELOG.md#214-2024-01-10

I wasn't sure whether I should open a new ticket to ask about this, or look a little deeper into the code to answer the question myself.
