### ISSUE TITLE
Support tagging in format project-name/x.y.z

### ISSUE THREAD

**Issue by DaSchTour** [jscutlery/semver#589]
It would be great if tags would also be possible in the format `project-name/x.y.z` as these are for example in Fork collapsed like folders and make navigating them a lot easier.

**Comment by mmt-trackunit** [comment]
Can't you set `tagPrefix` inside your NX project.json?

We are using this in our config:

```
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "tagPrefix": "${projectName}/",
        ...
      }
    },
```

**Comment by DaSchTour** [comment]
Well. TagPrefix somehow made me think that's some that is added before the regular tag beeing projectName-X.Y.Z 😅 so that it would be PREFIXprojectName-X.Y.Z
