### ISSUE TITLE
feat: Add support for Nx project without a root configuration file (angular.json, workspace.json)

### ISSUE THREAD

**Issue by NachoVazquez** [jscutlery/semver#600]
## The Problem

The latest versions of Nx (see [14.2.1](https://github.com/nrwl/nx/releases/tag/14.2.1)) support creating Nx workspace without an `angular.json`, `workspace.json` or `nx.json`.

However, when trying to run the `nx version <my-project>` in a workspace with that characteristic I get the following error.

` Error: ENOENT: no such file or directory, open '<path-to-my-project>/angular.json'`

## Acceptance Criteria

I should be able to use the version generator in a workspace with an `angular.json` file.

**Comment by NachoVazquez** [comment]
I'm working on a PR to support this feature.

**Comment by weiwen-chi** [comment]
Hi @NachoVazquez, is there a workaround for this? I guess what I really want to check is what specific setting semver is trying to get from angular.json

**Comment by NachoVazquez** [comment]
Hi @weiwen-chi ! I have a PR open and ready for review fixing this issue https://github.com/jscutlery/semver/pull/603

The problem is that semver is trying to read the project roots from the `angular.json` or `workspace.json`.

Luckily this information is already provided for us from the `ExecutorContext`.

With the changes, I've suggested the code of the plugin should be simplified.

**Comment by picosam** [comment]
Hello, so until this PR gets merged, how could we, say, make the default base branch to check against `main` instead of `master`?

**Comment by NachoVazquez** [comment]
Hi @picosam , this PR doesn't solve that. It only deals with the way projects in the monorepo are discovered by the plugin.
