### ISSUE TITLE
Upgrade @nrwl/devkit peer dependency to ^15

### ISSUE THREAD

**Issue by boy51** [jscutlery/semver#616]
I have to use force install in my repo currently due to this library listing @nrwl/devkit@14 as a peer dependency

According to PR #615  the peer dependency can be upgraded.

**Comment by Chowarmaan** [comment]
npm ERR! Conflicting peer dependency: @nrwl/devkit@14.8.6
npm ERR! node_modules/@nrwl/devkit
npm ERR!   peer @nrwl/devkit@"^14.0.0" from @jscutlery/semver@2.27.2
npm ERR!   node_modules/@jscutlery/semver
npm ERR!     dev @jscutlery/semver@"^2.26.0" from the root project

I have the same issue, and without the --force, semver stopped working in my repository, with Nrwl NX 15.
