### ISSUE TITLE
Azure pipeline tags

### ISSUE THREAD

**Issue by shell-davidbani** [jscutlery/semver#622]
While running in Azure pipeline `nx run-many --all --target=version --parallel=1`, outputs the following: 

```
🟢 Nothing changed since last release.
```

Example in project.json:

```
"version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional",
        "baseBranch": "main",
        "syncVersions": true
      }
    }
```

Any reason why the latest git tag is not found? The git history contains previous tags, for example:

```
commit #### 
commit #### 
commit #### (tag: v0.0.5) <- latest
commit #### 
commit #### 
commit #### (tag: v0.0.4)
```

Running `nx run-many --all --target=version --parallel=1` _locally_ works as expected.

**Comment by edbzn** [comment]
@shell-davidbani I'm not an Azure wizard but have you added the `fetchDepth: 0` property in your pipeline?

**Comment by shell-davidbani** [comment]
Decided to use changsets as an alternative.
