### ISSUE TITLE
versionTagPrefix not propagated when checking dependencies' versions

### ISSUE THREAD

**Issue by mauris** [jscutlery/semver#624]
I have changed my config's `tagPrefix` to `release/${projectName}/` for all projects in my NX monorepo, but when checking for inter-dependencies' versions, it reverts back to `${projectName}-` instead.

It turned out that `versionTagPrefix` was not propagated to `tryBump` in `packages/semver/src/executors/version/index.ts` Line 80 to 91. 

Is this intended?

**Comment by mauris** [comment]
If this is a bug, I can open a fix

**Comment by edbzn** [comment]
Hi, I'm not sure what you mean by "when checking for inter-dependencies versions", the tag prefix is not propagated when using --trackDeps flag? Anyway, if the tag prefix is not propagated it's certainly a bug.

**Comment by mauris** [comment]
Yes, I have `trackDeps` set to `true`. This is my `version` target in `project.json`:

```json
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional",
        "push": false,
        "syncVersions": false,
        "trackDeps": true,
        "skipCommitTypes": ["docs", "ci", "release"],
        "tagPrefix": "release/${projectName}/",
        "commitMessageFormat": "release(${projectName}): version ${version} [ci skip]"
      }
    },
```

The tag prefix does not get propagated. The fix I've identified it to be at this call to `tryBump`:

```typescript
  const newVersion$ = tryBump({
    preset,
    projectRoot,
    dependencyRoots,
    tagPrefix,
    versionTagPrefix, // <-- this is currently missing
    releaseType: releaseAs,
    preid,
    syncVersions,
    allowEmptyRelease,
    skipCommitTypes,
    projectName,
  });

```

**Comment by edbzn** [comment]
I see, you're right we need to reformat the tag correctly when checking for the dependencies. I'm re-reading this part of the code, and I have to say the logic inside the `tryBump` is unreadable, it probably needs refactoring.
