### ISSUE TITLE
Error:  > NX  Cannot update Project header at packages/header. It doesn't exist or uses package.json configuration.

### ISSUE THREAD

**Issue by MuthupandiG** [jscutlery/semver#634]
Hi Team,
I have upgraded my monorepo from **Lerna (v3)** to **Nx (v15)** and I m using workspaces config in package.json for dependency installation instead of lerna bootstrap and the **Node Env is v16.5** However, I am getting below error when running 

_nx g @jscutlery/semver:install_

**package.json config:**

_"workspaces": [
    "packages/**"
  ]_

**Selected Options:**
>  NX  Generating @jscutlery/semver:ng-add

✔ Lock/sync versions between packages? (y/N) · false
✔ Enforce conventional commits? (Y/n) · true
? Which projects would you like to version independently? Selected Header project

**And, the error is:**
 > NX  Cannot update Project header at packages/header. It doesn't exist or uses package.json configuration.

**Comment by MuthupandiG** [comment]
**Verbose error:**

Cannot update Project header at packages/header. It doesn't exist or uses package.json configuration.
    at validateProjectConfigurationOperationsWithoutWorkspaceJson (/Users/xxxx/Documents/Lerna_Nx/projectA/node_modules/@jscutlery/semver/node_modules/@nrwl/devkit/src/generators/project-configuration.js:355:15)

**Comment by edbzn** [comment]
@herrlegno can you provide the output of `nx report` please?

**Comment by herrlegno** [comment]
> @herrlegno can you provide the output of `nx report` please?

![image](https://user-images.githubusercontent.com/11634168/224341568-e8772492-39a7-459b-a02d-687729ed2cd8.png)

**Comment by herrlegno** [comment]
@edbzn is there a way to migrate from package.json to project.json that seems to be the way to be able to use this versioning plugin?

**Comment by herrlegno** [comment]
@edbzn I found a workaround to make it work. Just add a project.json file with:

```json
{
  "name": <project name>,
  "targets":{}
}
```

before running

```bash
ng g @jscutlery/semver:install
```


It will add the nx runners to it, and if you run:
```bash
nx affected --target version [...options]
```

after the commits it will run as expected.

For reference after doing what I described in one of my packages I this project.json:

```json
{
  "name": "eslint-config",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "targets": {
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional"
      }
    }
  }
}
```

**Comment by herrlegno** [comment]
@edbzn Today I wanted to update a package but it's not working again:

![image](https://user-images.githubusercontent.com/11634168/227233514-54643194-70c2-4902-bba4-ca97baefb49c.png)

It doesn't detect the changes

**Comment by herrlegno** [comment]
Kinda works but it creates a version for the others packages even though I didn't make any changes to them. Also process are run in parallel and git doesn't like that

![image](https://user-images.githubusercontent.com/11634168/227249991-03065b5f-84a9-411c-8a73-08010a829492.png)

**Comment by herrlegno** [comment]
Kinda works but It creates also versions for packages that are not modified. Also git is executed in parallel and it doesn't like to do that:

![image](https://user-images.githubusercontent.com/11634168/227250554-31cdd579-9789-4184-9392-04a1f0d563a9.png)

**Comment by edbzn** [comment]
Yeah, you have to explicitly give --parallel=1 for the concurrent Git access, anyway run-many is not what you need. I checked and it seems that actually, our executor is not compatible with package.json based projects. This is something we need to consider in #655, but for now, you need to use a project.json file to be able to configure executors.

**Comment by herrlegno** [comment]
> @edbzn Today I wanted to update a package but it's not working again:
> 
> ![image](https://user-images.githubusercontent.com/11634168/227233514-54643194-70c2-4902-bba4-ca97baefb49c.png)
> 
> It doesn't detect the changes

@edbzn sorry for bothering you again. I just found the problem that i mentioned was because i was running affected version with basebranch main and the commits were on main so there was no change. After changing the base branch to origin/main it runs perfectly.

Running this (in my example) works as expected:

```bash
nx affected --target version --base=origin/main --parallel=1
``

![image](https://user-images.githubusercontent.com/11634168/227516725-bdc7044e-7bad-4bd5-924f-f2c3ab072fe1.png)

Sorry for all the trouble, first time using Nx + Automatic versioning.
