### ISSUE TITLE
docs: add compatibility overview 

### ISSUE THREAD

**Issue by mikelgo** [jscutlery/semver#638]
First of all: Thank you for this awesome lib! =) 

I have a small improvement request for the docs: It would be super helpful to have a overview about which version of `semver` is compatible with the respective nx version

I would also be happy to contribute this, I just need some time to dig through the changelog

**Comment by edbzn** [comment]
Good idea @mikelgo

**Comment by mikelgo** [comment]
I started to collect the data

**Comment by mikelgo** [comment]
@edbzn [PR created](https://github.com/jscutlery/semver/pull/640).
However I need some help there

**Comment by edbzn** [comment]
Close as completed, thank you @mikelgo!
