### ISSUE TITLE
Bug: releaseCommitMessageFormat preset option doesn't work

### ISSUE THREAD

**Issue by m3Lith** [jscutlery/semver#639]
The option `releaseCommitMessageFormat` doesn't seem to have any impact on the generated commit message.

My options look like this:

```
"options": {
        "preset": {
          "name": "angular",
          "releaseCommitMessageFormat": "chore(release): {{currentTag}} [skip ci]",
          "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
          "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/branches/compare/{{currentTag}}%0D{{previousTag}}",
          "issueUrlFormat": "https://barbora.atlassian.net/browse/{{id}}"
        },
        "tagPrefix": "${projectName}@"
      }
```

All the other formatting options work fine.

**Comment by PrinceJohn** [comment]
@m3Lith I have a similar problem, but my issue is that none of the preset options have any impact on the generated changelog.

Just out of curiosity, which version are you using?

**Comment by m3Lith** [comment]
Apparently there's an option called [`commitMessageFormat`](https://github.com/jscutlery/semver#commit-message-customization), which is taken into account, and not the conventional commits option `releaseCommitMessageFormat` under `preset`.
