### ISSUE TITLE
Missing workspace.json 

### ISSUE THREAD

**Issue by petergrau** [jscutlery/semver#64]
When executing `nx run workspace:version --sync-versions true --root-changelog false` in my nx repo I get the following warning: 

```
(node:7184) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'project/workspace.json'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

NX version: `"@nrwl/workspace": "11.1.5"`

**Comment by edbzn** [comment]
@petergrau Could you provide a reproduction please? I will dig in it. However the path `'project/workspace.json'` seems not correct  at first look but I need to have more context.

**Comment by petergrau** [comment]
> @petergrau Could you provide a reproduction please? I will dig in it. However the path `'project/workspace.json'` seems not correct at first look but I need to have more context.

I added semver using `ng add @jscutlery/semver` and then executed `nx run workspace:version --sync-versions true --root-changelog false`. (Adding it complete without an error.)

(`project` was the replacement for the path to the nx workspace)

**Comment by edbzn** [comment]
Oh ok I didn't noticed it was a warning. I see now, it's because we're reading the `angular.json` file this way :

```ts
return readJsonFile(resolve(workspaceRoot, 'workspace.json')).pipe(
  catchError(() => readJsonFile(resolve(workspaceRoot, 'angular.json')))
);
  ```
  
We should check if the file exist before reading it, but I don't get why an unhandled promise is raised, we're actually handling the error notification.

**Comment by yjaaidi** [comment]
Thanks @petergrau for the issue.

There was actually a problem with the `readJsonFile` function as it is using `from` instead of `defer`. If the error is triggered before we subscribe and implicitly add an error catcher, it would crash. I am sharing a fix right now.

@edbzn Actually, I am more in favor of the pythonic approach of "Easier to Ask for Forgiveness than Permission" https://docs.python.org/3.9/glossary.html#term-eafp instead of https://docs.python.org/3.9/glossary.html#term-lbyl 🐍

**Comment by edbzn** [comment]
I didn't know about these approaches and I love it! I use it in real life too, so why not in code. :smile:

**Comment by yjaaidi** [comment]
It also works in the mountains. If I fall then it's a hole 😅.
