### ISSUE TITLE
Support for configuraton in postTargets

### ISSUE THREAD

**Issue by jbadeau** [jscutlery/semver#645]
Hello,

One thing that would be really nice is support for optionally including configuration on postTargets like:

```javascript
{
  "postTargets":["project:target:configuration"]
}
```

This way I can select the production configuration on in ci.

**Comment by edbzn** [comment]
Hi @jbadeau, 

I think you can already pass a configuration, under the hood we use `parseTargetString` from Nx devkit which allows passing a configuration like so `'proj:test:production'`.

Did you try it?

**Comment by jbadeau** [comment]
Nooooo I didn’t and I totally ashamed I didn’t try
