### ISSUE TITLE
syncVersions only create a new changelog for affected libraries

### ISSUE THREAD

**Issue by petergrau** [jscutlery/semver#66]
I guess the following "works as designed" but can cause problems: 

When using the following setting: 

```
    "workspace": {
      "architect": {
        "version": {
          "builder": "@jscutlery/semver:version",
          "options": {
            "syncVersions": true
          }
        }
      },
      "root": "."
    }
```

the changelog is only created for some libraries - probably `affected` ? But when keeping all the versions in sync I always need to publish a new version of all libs - no matter if they are affected or not. So the package.json should be updated in any case and probably an empty changelog as well? At least that is the standard behaviour when using something like [standard-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/standard-changelog)

**Comment by petergrau** [comment]
When #65 worked this one also touched all libs. Not sure what caused it before.

**Comment by edbzn** [comment]
In sync mode all librairies get updated even if they are not affected, it work as expecting. Let us know if this append again. I'm closing this for now.
