### ISSUE TITLE
workspace.json got removed with Nx v15.7.0

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#666]
Hi @edbzn 

With the "workspace": "" hack in workspace.json we used to get semver to work in a v2 workspace. Now that workspace.json is gone, how will this affect @jscutlery/semver?

Cheers,
Bjorn

**Comment by edbzn** [comment]
Hey, it should still work with the hack but I'm not 100% sure as I need to test it manually. Let me know if it brings problems. In any case enterly refactoring semver is becoming very needed but I can't promise any date.

**Comment by pongells** [comment]
What is the workaround? 

Creating a workspace.json that contains only
```
{
  "workspace": ""
}

```
I am getting:
```
nx run workspace:version --dryRun         

 >  NX   workspace.json is ignored

   Nx no longer reads configuration from workspace.json.
   Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.


 >  NX   Cannot find project 'workspace'

```

**Comment by bjornharvold** [comment]
Hi @pongells 

This is what my root project.json looks like. After the removal of workspace.json, this is the only reference to semver in my project.

```
{
  "name": "workspace",
  "$schema": "node_modules/nx/schemas/project-schema.json",
  "targets": {
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "syncVersions": true,
        "commitMessageFormat": "chore(${projectName}): publish version ${version}"
      }
    },
    "github": {
      "executor": "@jscutlery/semver:github",
      "options": {
        "target": "master",
        "tag": "${tag}",
        "notes": "${notes}"
      }
    }
  },
  "tags": []
}

```

**Comment by pongells** [comment]
Thanks,

I managed to make it work by slightly tweaking your example:

```
{
  "name": "workspace",
  "$schema": "node_modules/nx/schemas/project-schema.json",
  "targets": {
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "preset": "conventional"
      }
    }
  },
  "tags": []
}
```
 
and creating an empty CHANGELOG.md in the root.

Running: `nx run workspace:version` seems to be filling the global changelog :)

**Comment by haskelcurry** [comment]
There is no root project.json anymore, too. The projects are inferred now: https://nx.dev/deprecated/workspace-json  
Any suggestions?

**Comment by bjornharvold** [comment]
I can confirm that @jscutlery/semver works fine with Nx ^v15.7.0. 

Closing

**Comment by bjornharvold** [comment]
@haskelcurry with all due respect. What you are referring to is not related to my ticket (this one). This plugin works as expected with the latest version of Nx. 

The issue you're having was mentioned here https://github.com/jscutlery/semver/issues/666#issuecomment-1442722196 already with a solution.

**Comment by haskelcurry** [comment]
@bjornharvold with respect, too, but please hear me out. In the comment you're refering to, you say:
> This is what my root project.json looks like  

But now in latest version of Nx **there is no root project.json** file. Which means that no, it IS related to this ticket imo.  
But it's up to you to decide of course.

**Comment by edbzn** [comment]
I think there's a misunderstanding @haskelcurry, the Nx doc has the following statement: 

> Projects can be configured in package.json (if you use npm scripts and not Nx executors) **and project.json** (if you [use task executors](https://nx.dev/plugin-features/use-task-executors)). Both package.json and project.json files are located in each project's folder. Nx merges the two files to get each project's configuration.

You can use both, project.json and pakcage.json configuration in the same workspace, project.json isn't deprecated, only workspace.json was.

> there is no root project.json file

Of course, this is a hack for semver to deal with sync mode to run an executor against the whole workspace.

**Comment by haskelcurry** [comment]
@edbzn They just didn't update the documentation yet. Here's what happens if you add the workspace.json file manually:  
```
>  NX   workspace.json is ignored

   Nx no longer reads configuration from workspace.json.
   Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.
```

**Comment by haskelcurry** [comment]
@edbzn There is **NO** confustion. There is no such thing as "root" project.json in Nx now. Therefore all the hacks mentioned here don't work anymore with the latest Nx.  
Follow the steps to reproduce it and see it yourself:  
https://github.com/jscutlery/semver/issues/683
