### ISSUE TITLE
Remove Angular CLI compat layer

### ISSUE THREAD

**Issue by edbzn** [jscutlery/semver#685]
cf: https://github.com/bikecoders/ngx-deploy-npm/issues/467#issuecomment-1486261214

**Comment by dianjuar** [comment]
A contributor may want to use [this PR as a reference](https://github.com/bikecoders/ngx-deploy-npm/pull/570).

In ngx-deploy-npm (another Nx Plugin), removed Angular Workspace compatibility. The coated PR may help on this quest.

**Comment by edbzn** [comment]
This is already done! I forgot to link the corresponding issue. Thanks @dianjuar.
