### ISSUE TITLE
 ❌ [object Object] error instead of SchemaError when using ngx-deploy-npm

### ISSUE THREAD

**Issue by therockstorm** [jscutlery/semver#686]
I'm getting the following output,

```
[eslint-config] 📜 Generated CHANGELOG.md.
[eslint-config] 📝 Updated package.json version.
[eslint-config] 📦 Committed "chore(eslint-config): release version 0.1.0".
[eslint-config] 🔖 Tagged "eslint-config-0.1.0".
[eslint-config] ❌ [object Object]
```

I'm using the config from the `README`,

```
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "noVerify": true,
        "postTargets": ["eslint-config:npm", "eslint-config:github"],
        "preset": "conventional",
        "trackDeps": true
      }
    },
    "github": {
      "executor": "@jscutlery/semver:github",
      "options": {
        "tag": "${tag}",
        "notes": "${notes}"
      }
    },
    "npm": {
      "executor": "ngx-deploy-npm:deploy",
      "options": {
        "access": "restricted",
        "dryRun": "${dryRun}"
      }
    }
```

I added some debug logs locally, and found that it's because of a `SchemaError`,

```
SchemaError {
  message: "Property 'dryRun' does not match the schema. '${dryRun}' should be a 'boolean'."
}
```

I see two issues,

1. The `[object Object]` error message [happening here](https://github.com/jscutlery/semver/blob/34c931a58e5d5a2eb19fde0997b15a2100caa91c/packages/semver/src/executors/version/utils/post-target.ts#L54).
2. `ngx-deploy-npm` expects a `boolean`, so the [`README` example](https://github.com/jscutlery/semver/blob/34c931a58e5d5a2eb19fde0997b15a2100caa91c/README.md?plain=1#L241) doesn't work. I changed it to `"dryRun": false` to get it working.

**Comment by edbzn** [comment]
Hi @therockstorm thanks for raising this issue. I'll have a look.

**Comment by dianjuar** [comment]
Hi @therockstorm 

ngx-deploy-npm `dry-run` option does not work with `"${dryRun}"`.
It should be a boolean.

`${dryRun}` could make sense on semver but on ngx-deploy-npm will not.

**Comment by therockstorm** [comment]
> ngx-deploy-npm `dry-run` option does not work with `"${dryRun}"`.
> It should be a boolean.
Agreed.

> `${dryRun}` could make sense on semver but on ngx-deploy-npm will not.
So what is the suggested fix? At the very least, the `README` example should be updated since it doesn't work.

**Comment by dianjuar** [comment]
To be able to pass parameters to post-targets, it would require a feature on semver probably. Issue #696 is requesting that.

I do agree that the README should be updated with examples that are valid.

**Comment by edbzn** [comment]
Fixed in https://github.com/jscutlery/semver/releases/tag/semver-5.0.0, thanks for reporting!
