### ISSUE TITLE
Nx 16 support

### ISSUE THREAD

**Issue by why-this-code-works** [jscutlery/semver#697]
Nx 16 s here: https://github.com/nrwl/nx/releases/tag/16.0.0

It'd be great to support the new major, thank you 🙌

**Comment by edbzn** [comment]
Hey, will manage to support it soon, our automated migration is failing.

**Comment by why-this-code-works** [comment]
Yes, there are some breaking changes. I think it should be a new major release of `@jscutlery/semver` as well, so the previous one will continue to work with Nx 15.

**Comment by why-this-code-works** [comment]
Confirming that v3 is working fine, thanks a lot! 🎉

**Comment by edbzn** [comment]
@dianjuar is your man
