### ISSUE TITLE
Unable to get a major version bump using BREAKING

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#698]
Hi @edbzn 

I just updated our codebase to Angular 16 and we like to use to have our own main version follow Angular's. I migrated to 16 and then committed with a BREAKING in the commit.

```
:arrow_up: build: migrated to Angular 16

That was easy!

BREAKING: Major Angular version bump.
```

That was the only commit and when I ran:
`npx nx run workspace:version --skipProjectChangelog=true`

The plugin only updated the minor version.

What needs to be in the commit text for your plugin to do a major version bump?

Cheers 🍺

**Comment by edbzn** [comment]
Hi @bjornharvold, if you are using Angular's preset (default one): 

```
feat: allow provided config object to extend other configs

BREAKING CHANGE: `extends` key in config file is now used for extending other config files
```

If you are using the Conventional preset there's a shortcut using `!`:

```
feat(api)!: send an email to the customer when a product is shipped
```

**Comment by bjornharvold** [comment]
🙇🏼‍♂️
