### ISSUE TITLE
Combine semver with GitHub release

### ISSUE THREAD

**Issue by petergrau** [jscutlery/semver#70]
We are currently using `semantic-release` but `semver` could be the perfect replacement. However there is on scenario that I am struggling with: Besides creating the changelog we also want to publish a GitHub release

- The problem is that `semver` will end the process with creating a tag.
- If I now e.g. want to use the `gh cli` to create a release I would be in trouble because the tag has already been created

Is there a smart way out of that?

**Comment by yjaaidi** [comment]
Hi @petergrau, I am not sure if the presence of the tag affects `gh cli`.

As mentioned by @edbzn in #71, we are thinking about the best way to handle publishing/deployment as we are not only aiming monorepos with libs but also monorepos with apps and maybe non-js code.

Meanwhile we provide a generic way for handling publishing & deployment, you could implement github release with something like this for each package
```sh
gh release create $(cat package.json | npx json version)
```

**Comment by petergrau** [comment]
> Meanwhile we provide a generic way for handling publishing & deployment, you could implement github release with something like this for each package
> 
> ```shell
> gh release create $(cat package.json | npx json version)
> ```

@yjaaidi thanks - that seems to work - need to dig in a bit deeper. The only remaining question I then have at this point is if there is a good way to only retrieve the changelog from the latest release from the CHANGELOG.MD that was written by semver.

**Comment by yjaaidi** [comment]
Closing this issue to regroup the discussions here #167.

**Comment by yjaaidi** [comment]
😅 Oups! I closed this too quickly.
AFAIK, there is no github release angular/nx builder meaning that after #167 is ready, we'll have to create one or create a schematic that adds an nx custom command running `gh release create` to workspace.json
