### ISSUE TITLE
Upcoming release date

### ISSUE THREAD

**Issue by lucavb** [jscutlery/semver#722]
Hey,

a while back we merged this PR together https://github.com/jscutlery/semver/pull/708 and I was wondering when you were planning on doing the next release? We are currently still using a fork that I made of this project and would like to switch back to the published version.

Thanks in advance :)

**Comment by edbzn** [comment]
@lucavb Sorry we had trouble releasing the lib due to a problem in Nx itself, I reported the issue and waited to get a fix to release. I found a workaround without the patch and just published the new version of semver. Thank you.
