### ISSUE TITLE
projectName is interpolated by NX now

### ISSUE THREAD

**Issue by mpsanchis** [jscutlery/semver#725]
Hi guys,

Note that `{projectName}` is interpolated by NX now, even in the project.json file.

I wanted to make a PR for this, but it's becoming a bit long and unfortunately I have to do other things. The changes I see are:
* README.md (first and foremost, when suggesting people to write `"tagPrefix": "${projectName}@"` or commit messages that contain stuff like `chore(${projectName})`)
* functions `formatTagPrefix` and `createTemplateString`
* unit tests

Cheers

**Comment by limonte** [comment]
Experiencing this issue too

**Comment by edbzn** [comment]
This was fixed in version 3.3.0, thanks for reporting.
