### ISSUE TITLE
targetDependencies is removed in Nx 16+

### ISSUE THREAD

**Issue by bencat-sixense** [jscutlery/semver#733]
Hi there ! 

As you may know, `targetDependencies` was removed from Nx 16, so we need to use `targetDefaults`
I would like to know what's the new way to add `version` in `nx.json` ?

I'm talking about this part of the README: https://github.com/jscutlery/semver#tracking-dependencies

I'm not sure about my understanding and I'm a bit lost since yesterday...

Thanks everyone !

**Comment by bencat-sixense** [comment]
I did this, and it seems to work:

` "targetDefaults": {
    ...
    "versioning": {
      "dependsOn": [
        {
          "target": "versioning",
          "projects": "dependencies"
        }
      ]
    }
  }`
  
Am I right ?

Thanks :)

**Comment by edbzn** [comment]
Hey @bencat-sixense, yeah the correct usage would be:

```json
  "targetDefaults": {
    "versioning": {
      "dependsOn": [
        "^versioning"
      ]
    }
}
```

I will update the documentation.
