### ISSUE TITLE
Preset Schema doesn't match the DOCs

### ISSUE THREAD

**Issue by viniciusLouzada** [jscutlery/semver#736]
Hello!

On the DOC it says that the preset option from the plugin executor can be of type `string | object`, but when I try to pass and object to specify some custom configs, I get the following error:

<img width="526" alt="image" src="https://github.com/jscutlery/semver/assets/40527798/91b2926f-c58a-4ff6-9ed8-5ebe82d99448">

The specific custom config that I'm trying to pass is to add more commit types to my CHANGELOG, like `refactor` and `chore`. Is there another way that I can achieve this??

**Comment by edbzn** [comment]
Hi @viniciusLouzada, you can configure the preset this way:

```json
  "version": {
    "executor": "@jscutlery/semver:version",
    "options": {
      "preset": {
        "name": "conventionalcommits",
        "types": [
          { "type": "feat", "section": "Features" },
          { "type": "fix", "section": "Bug Fixes" },
          { "type": "chore", "section": "Chores" },
          { "type": "build", "section": "Build System" },
          { "type": "ci", "section": "Continuous Integration" },
          { "type": "docs", "section": "Documentation" },
          { "type": "style", "section": "Styles" },
          { "type": "refactor", "section": "Code Refactoring" },
          { "type": "perf", "section": "Performance Improvements" },
          { "type": "test", "section": "Tests" }
        ]
      }
    }
  }
```

I just updated the documentation, thank you.

**Comment by viniciusLouzada** [comment]
Great, works perfectly!! Thank you very much, @edbzn!
