### ISSUE TITLE
Bug: Changelog template not included in npm package

### ISSUE THREAD

**Issue by kunyan** [jscutlery/semver#739]
Version: 3.3.0

When I run `nx g @jscutlery/semver:install`, after selected apps I need. then got error:
```
generateFiles: No files found in "/Users/kyan/test-demo/node_modules/@jscutlery/semver/src/generators/install/__files". Are you sure you specified the correct path?
```

I checked the code from npm, https://www.npmjs.com/package/@jscutlery/semver?activeTab=code there are no `__files` exists

**Comment by dhatawesomedude** [comment]
I experienced this error as well. Doesn't seem to be there with version 3.1.0

**Comment by materazu** [comment]
maybe a file missing in the last release? same problem here.
