### ISSUE TITLE
Version task never returns with nx 17 and version 4.0.0

### ISSUE THREAD

**Issue by bardisg** [jscutlery/semver#743]
I am using "@jscutlery/semver": "4.0.0" along with "nx": "17.0.2"

My version target is configured in project.json as :

```
"version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "baseBranch": "main",
        "preset": "conventional",
        "tagPrefix": "{projectName}@",
        "trackDeps": true,
        "releaseAs": "prerelease",
        "preid": "beta"
      }
    },
```

When I execute:

nx run version

I can see the logged message for next version calculation "Calculated new version "x.x.x".

Then the process hangs there as if no success or error is ever returned in the runSemver$.pipe https://github.com/jscutlery/semver/blob/main/packages/semver/src/executors/version/index.ts#L205C10-L205C10

Without the "preset": "conventional" seems to work as expected

**Comment by bardisg** [comment]
Seems like the  latest version of commitlint 18 bumped its dependency  conventional-commits-parser to version 5.

downgrading commitlint to its latest v17 will also change conventional-commits-parser to version 4 and things work again

**Comment by StevenCederrand** [comment]
I've recently updated my mono repo to  use `commitlint:18` which caused all of my releases to hang 😅 
There seem to be 30bugs, any idea on how long it would take to have this looked into?

**Comment by edbzn** [comment]
Could you try updating semver to v4.1.0 along with commitlint v18? I believe it's a version conflict with commitlint transitive dependencies. I wrote an e2e test (https://github.com/jscutlery/semver/commit/945c83d16246091213c1844da7d6e39f2e8d3963) to ensure it's not related to the preset.

**Comment by edbzn** [comment]
I'm going to close, feel free to reopen if still encountered.
