### ISSUE TITLE
Version calculate issue

### ISSUE THREAD

**Issue by maianhkhadev** [jscutlery/semver#773]
Hi all,

I have an problem with version calculate, we have version like this: x.y.z

When I deploy, version will increase z: E.g: 0.0.1, 0.0.2.
When my friend deploys, version will increase y: E.g: 0.1.0, 0.2.0.

I don't know what is the issue. It is normal with other projects.
Does anyone got the same problem? it is not critical but annoying for sprint release.

**Comment by edbzn** [comment]
Hard to tell without more context, what is the commit history, last tag, etc... I'll close this, feel free to provide more details so we can help you.
