### ISSUE TITLE
Missing Support for @nx/devkit v20.x.x

### ISSUE THREAD

**Issue by tuffz** [jscutlery/semver#910]
Hello,

First of all thank your for this amazing package!

I noticed that the Nx 20 release was officially published already on October 7th, but it seems this package doesn't yet support the new version. I'm just wondering if there are any plans to add support for Nx 20.x.x soon?

**Comment by edbzn** [comment]
Support for Nx 20 released in v5.5.0. Sorry for the time it took me. :slightly_smiling_face:
