### ISSUE TITLE
Versioning fails intermittently in projects with several modules

### ISSUE THREAD

**Issue by Katona** [jscutlery/semver#95]
Hi,

Versioning fails frequently in a project containing several modules, see this repo: https://github.com/Katona/nx-version-test. The problem seems to be that CHANGELOG files are generated and added to the git repo concurrently, and while one of the processes is adding the file the git repo is locked. 

I am using `@jscutlery/semver@1.3.2` and `nx@11.0.20`.

**Comment by yjaaidi** [comment]
Nice catch @Katona! Thx for the diagnostic.

**Comment by Katona** [comment]
Thanks, I didn't make a thorough investigation and I am not familiar with RxJs, so it was an educated guess. Is there any way I could contribute?

**Comment by edbzn** [comment]
Hi @Katona, 

Thanks for your feedback! Actually the workspace release work as the following : 

1. resolving all projects
2. concurrently by project
  2a. generate project's changelog
  2b. git add :arrow_left: _here is the problem, we should do this sequentially after changelogs get generated_
3. run standard version

We should modify the [`updateChangelog`](https://github.com/jscutlery/semver/blob/8eada0d59864d18b9bcefcfec36068e79dc79c38/packages/semver/src/builders/version/utils/changelog.ts#L42) function to extract the `git add` and move it after the [`forkJoin`](https://github.com/jscutlery/semver/blob/05e4d7632b04e0180ce973e6c050de18b24d602f/packages/semver/src/builders/version/version.ts#L33) operator in a dedicated function. This should look something similar to this :

```ts
getProjectRoots(workspaceRoot).pipe(
  switchMap((projectRoots) =>
    forkJoin(
      projectRoots
        .filter((projectRoot) => projectRoot !== workspaceRoot)
        .map((projectRoot) =>
          updateChangelog(...)
        )
    )
  ),
  switchMap((changelogPaths) => addToGitStage(changelogPaths))
)
```
We should pass the generated changelog paths to the git add function. Let me know if you want to fix this.

**Comment by Katona** [comment]
Hi @edbzn,

Thanks for help, I will try to fix it.

Gabor
